### ISSUE TITLE
rfc: size_t vs u64

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#102]
In the libimageflow API, we regularly pass buffer lengths around. As pointer sizes are platform-dependent, so are buffer lengths (typically). 

size_t == u32 on x86, size_t == u64 on x86_64. 

Now, we also *write* buffer lengths as out parameters. Imageflow is setting bytes in the client memory space when this occurs, so the client must be sure to reserve the appropriate size (u32 or u64) depending on the architecture. This is usually best accomplished by reserving the size of the pointer type.  C#, for example, only offers the IntPtr and UIntPtr types as platform-sized integers. Using it for lengths and counts is semantically icky. 

Options for buffer/byte/count values:

* Both in and out parameters use platform-dependent sized unsigned integers
* In parameters are platform-dependent, out parameters are always u64 (current). 
* Both in and out parameters always use u64.

**Comment by SamuelEnglard** [comment]
I'd vote for Both in and out parameters always use signed int64. Reason for signed is that .NET prefers Int64 over UInt64

**Comment by nathanaeljones** [comment]
Platform APIs for dealing with buffers always use unsigned lengths (regardless of OS).

Signed<>Unsigned conversion is a common cause of segfaults. I'd propose that:

1. Imageflow refuses to accept or write buffer lengths that exceed MAX_VALUE / 2 in unsigned representation (i.e, have their most significant bit set). I.e, max 31 and 63 bits usable for lengths.

This would permit you to define your P/Invoke signatures as Int64 if you like. Internally, our use of integers will be determined by what minimizes security risk and does not unnecessarily limit input.

2. Casting:

APIs in .NET which deal with buffer lengths are quite inconsistent. 31 bits is the lowest common denominator. 

I want to be consistent across the Imageflow API with this, but I'm not OK with limiting the maximum buffer length to 2,147,483,647 at the permanent API level. I would suggest that regardless of design, it will be necessary to bounds check lengths to 0..2,147,483,647 (or less, if you're doing math), and fail the operation from the wrapper otherwise.

**Comment by nathanaeljones** [comment]
There's no technical difficulty in having a UIntPtr out parameter in .NET, is there? This question holds more relevance for languages that might lack that data type.

**Comment by SamuelEnglard** [comment]
The reason .NET prefers Int64 over UInt64 is because the .NET specification does not guarantee that languages compiling down to it support unsigned integers (except for byte)

**Comment by nathanaeljones** [comment]
CLS compliance shouldn't matter for P/Invoke signatures, those are internal. Wrappers can always choose to be CLS complaint or not. As far as constraining the languages a wrapper can be written in, it seems unlikely that any .NET language would be able to P/Invoke, yet lack UInt64. VB, C#, and F# support Uint64.

**Comment by SamuelEnglard** [comment]
Yes most likely the wrapper doesn't have to be CLS compliant but if I read in a UInt64 and have a number larger than is supported by Int64 my options are ugly.  I'm willing to do them if you think the limitation of Int64 is important enough.

**Comment by nathanaeljones** [comment]
If you read a UInt64, you have to ensure it is less than UInt64 / 2. If you read an Int64, you have to ensure it is >= 0.

My proposal (re signed/unsigned) is to simply ensure (at Imageflow's boundaries) that the most significant bit is always 0, regardless of integer size. This ensures that casting between signed/unsigned versions can always succeed, as the bit representation works regardless of whether you consider it signed or unsigned. 

As far as sizing goes on .NET, you still have to set `gcAllowVeryLargeObjects` to even deal with arrays over 2GB. It's probably best if you just raise an exception if any buffer length exceeds Int32.MaxValue or is less than 0.

**Comment by nathanaeljones** [comment]
Both Ruby-ffi and Node-ffi offer platform-dependent unsigned integers.  Javascript, however, [cannot represent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger) integers greater than (2^53 -1). 

Reviewing newer C libraries like Snappy, etc, which have widespread bindings, I think the size_t approach is cleanest, most expected, and widely supported. Managed languages with shorter integers or bitness limitations will have to bounds check no matter what.

**Comment by nathanaeljones** [comment]
This only applies to RAM buffer lengths. For file I/O (or any use outside of pointer arithmetic on RAM areas) I would stick with int64.

**Comment by SamuelEnglard** [comment]
Works for me

**Comment by nathanaeljones** [comment]
Ok, reverting to size_t for buffer lengths.
