### ISSUE TITLE
Official support for C# with .Net Core

### ISSUE THREAD

**Issue by CShepartd** [imazen/imageflow#108]
Hi,

I proposue to create official wrapper for C# with .Net Core. I know it was o goal in kickstarrter and not achieved ($125k stretch goal) but i still think its important for all this project. PHP and other languages have many libs with wrapppers but .Net Core is opportunity to "grab" almost all .Net community who want make graphic manipulation. I know about ImageSharp (old ImageProcessor Core) or Magick.NET but they are not like this project. ImageSharp have poor performance with full of glitches (i know, its alpha but in not going well) and Magick.NET working only on Windows with .Net Core. 

I know also about not official @SamuelEnglard binding for C# but making official will make .Net Core great at start

**Comment by SamuelEnglard** [comment]
What do you mean by "Official"? If you mean supported by Imazen I can't comment but I do plan to keep my C# bindings up to date, they will be part of this repo, and will support .NET Core (Currently targeting Standard 1.1)

**Comment by CShepartd** [comment]
In "official" I mean supported by Imazen. I'm glad about your work on wrapper but official support from Imazen will be better for both projects

**Comment by SamuelEnglard** [comment]
I think https://twitter.com/Shmuelie/status/747088899382587392 might answer your question?

**Comment by CShepartd** [comment]
@SamuelEnglard Semi cuz it was told about support for FFI bindings or REST API not "official" support C# binding. It's nice to join 2 projects (Imageflow and C# Binding) in one on GitHub but it does not mean anything specially when at 30.11.2016 @nathanaeljones sad "official support is for Ruby and eventually Node"

**Comment by nathanaeljones** [comment]
What does "official" mean to you? How would your expectations differ between official and "unofficial" bindings?

**Comment by CShepartd** [comment]
The same like you are calling some wrappers "official" and "unofficial"

https://github.com/imazen/imageflow/releases/tag/v0.0.7
> With community-provided language bindings (official support is for Ruby and eventually Node, but @SamuelEnglard is working on C# bindings.

**Comment by nathanaeljones** [comment]
The Kickstarter promised only Node and Ruby bindings. C#/.NET is a very time-expensive platform to develop for (and a rapidly moving target with .NET Core). To make any guarantees about C# development would require setting aside enough funds to cover the cost of those guarantees in a worst-case scenario (not unlikely if past .NET trends continue). 

Eventually, I plan to rewrite ImageResizer to use Imageflow, which means some kind of C# bindings (at least enough to support ImageResizer's features) will become as officially supported as ImageResizer is at that time. 

I do intend to help @SamuelEnglard with the C# bindings as much as I can, but I already have a large scope of work, and I don't plan to expand my public commitments. Imazen is a one-person company - myself - and I focus on open-source development. I don't have enough time to do proper marketing, so I rely on the community to advertise my paid licenses/services. It's not enough to avoid financial strain and severe stress, but I'm hoping that income will hold out long enough that I can do proper marketing for Imageflow after it's released and break the cycle.+

Not committing to delivering and maintaining an "official" C# wrapper doesn't mean that there won't be a very good C# wrapper available, or preclude me eventually offering "official" support for it. It sounds like you are focused on support guarantees. If so, I'd like to remind you that those only come with a support contract; I don't provide support guarantees to the general public for any of my projects, even if I do seem to answer questions on StackOverflow reliably. 

If this is something you care strongly about, perhaps you would like to contribute in some way to the development of the C# bindings? The faster that they mature, the sooner I can consider offering "official" support for them or the like.

**Comment by CShepartd** [comment]
Thanks for answering for my question. I supported OFC on kickstarter and was very disappointment when $125k goal was not arrived. So good luck and I have hope you have enought time to work on more than ruby/node wrappers

**Comment by nathanaeljones** [comment]
Thank you for your support!
