### ISSUE TITLE
Add JSON API to imageflow_server

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#112]
I'd like to wait until I get feedback on the imageflow_tool JSON API before I implement it in imageflow_server.

**Comment by gerneio** [comment]
@lilith just wanted to check to see when you think this would be implemented? I have no desire to right those complicated-looking JSON request objects and would much rather use a fluent API, but for features that do not yet have a Fluent API, this at least gives us an entry point. So for example, I noticed that FillRectangle doesn't seem to be exposed in imageflow_server, but is available in imageflow_tool. So my guess is that there are still quite a few methods/properties that aren't exposed in the Fluent API on imageflow_server yet.

**Comment by lilith** [comment]
imageflow_server is obsolete: https://github.com/imazen/imageflow/issues/598

**Comment by lilith** [comment]
Moved to https://github.com/imazen/imageflow-dotnet-server/issues/59
