### ISSUE TITLE
prefix :ir4_local: returns "File not found" but :static: works

### ISSUE THREAD

**Issue by mgaerber** [imazen/imageflow#113]
I can't get the server to work with the ir4_local prefix. 
```
λ imageflow_server.exe start --mount /img/:ir4_local:./images/ --data-dir ./data
release 0.0.13 (64aeef5df* 2017-01-09) for x86_64-pc-windows-msvc sandybridge
Listening on localhost:39876

vs

λ imageflow_server.exe start --mount /img/:static:./images/ --data-dir ./data
release 0.0.13 (64aeef5df* 2017-01-09) for x86_64-pc-windows-msvc sandybridge
Listening on localhost:39876
```

**Comment by nathanaeljones** [comment]
Does it work if you specify the physical path with backslashes?  (i.e. `.\images\`)

**Comment by mgaerber** [comment]
runs but still gives "File not found" (with or without trailing backslashes):
```
λ imageflow_server.exe start --mount /img/:ir4_local:.\images --data-dir .\data
release 0.0.13 (64aeef5df* 2017-01-09) for x86_64-pc-windows-msvc sandybridge
Listening on localhost:39876
```

Crash:
```
λ imageflow_server.exe start --mount /img/:ir4_local:.images --data-dir .\data
release 0.0.13 (64aeef5df* 2017-01-09) for x86_64-pc-windows-msvc sandybridge
thread 'main' panicked at 'Failed to mount /img/ using engine ir4_local (MountLocation { prefix: "/img/", engine: Ir4Local, engine_args: [".images"] })
("Error { repr: Os { code: 2, message: \"Das System kann die angegebene Datei nicht finden.\" } }")
Current dir: Ok("F:\\Tools\\imageflow")', src\lib.rs:591
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by nathanaeljones** [comment]
What if you *don't* use slashes? It looks like you might need `\\`.

**Comment by mgaerber** [comment]
hm, I think I tried all possible variants. Oddly, it works with the :static: prefix - probably something about the extra checking in ir4_local_handler at https://github.com/imazen/imageflow/blob/c14ead1f9ac81cedb32e09d723ea919d3e337185/imageflow_server/src/lib.rs#L424

**Comment by nathanaeljones** [comment]
Well, my integration tests only covered static, ir4_http, and permacache_proxy_guess_content_types.  I'll add tests for ir4_local. 

static actually has a different impl: https://github.com/iron/staticfile/blob/master/src/requested_path.rs

**Comment by nathanaeljones** [comment]
Actually, I *did* have tests, but not with a subfolder.

**Comment by nathanaeljones** [comment]
Can you repro with this build? https://ci.appveyor.com/project/imazen/imageflow/branch/master

I didn't fix it (I don't think), but it's also passing integration tests with a variety of paths. 

By design, ".images" won't work, but  --mount /img/:ir4_local:.\images should, as should  --mount /img/:ir4_local:images

**Comment by nathanaeljones** [comment]
Ignore the above. I think I've reproduced this.

**Comment by mgaerber** [comment]
Ok, I see the build is currently failing, I'll try with the next snapshot again

**Comment by nathanaeljones** [comment]
This build should resolve the issue: https://ci.appveyor.com/project/imazen/imageflow/build/577

**Comment by mgaerber** [comment]
Nice!
![imageflow-server](https://cloud.githubusercontent.com/assets/1120707/22242392/7afebc4a-e223-11e6-9526-79b319486bdd.png)

**Comment by nathanaeljones** [comment]
Thank you for reporting this. There was a very subtle bug in the integration tests that was hiding certain failures. Also - the next build should support HTTPS
