### ISSUE TITLE
Implement support for animated GIFs

### ISSUE THREAD

**Issue by stravid** [imazen/imageflow#116]
I finally found some time to play around with the latest release. I discovered that an animated GIF produces following error:

~~~
Internal Server Error
Info:"/Users/david/Downloads/imageflow/images/2.gif"
Error:BuildFailure(Error { httpish_code: 500, message: "Err(FlowErr { code: 40, message_and_stack: \"Not implemented : Unrecognized leading byte sequence 4749463839618002\\ncodecs.c:211: in function flow_codec_select_from_seekable_io\\n\" })" })
~~~

**Comment by nathanaeljones** [comment]
Thank you for trying it out! 

No form of GIF is supported at this time; due to low demand they were de-prioritized (but will be supported in the final 1.0 release). 

Is GIF support important for your immediate use case? If so, we can bump up the priority a bit.

**Comment by stravid** [comment]
You are welcome, I'm really looking forward to give it a real spin in a side project.

In my use case around 10% of all images are GIFs, mostly animated. But I'm in no hurry, so please don't alter your plan for a single person :)

Additional feedback that's probably more actionable right now: It took me a while to figure out a working value for the `--mount` option. As someone with zero knowledge it looked pretty cryptic at first glance.

**Comment by nathanaeljones** [comment]
Would you suggest an alternate syntax for `--mount`, or just better examples and documentation?

**Comment by stravid** [comment]
I would go down the examples / documentation road.

**Comment by nathanaeljones** [comment]
Animated gifs are supported in the latest commit. All gifs repeat indefinitely; repeat extension cloning blocked by https://github.com/PistonDevelopers/image-gif/issues/40

Gifs are not optimized - each frame occupies the entire canvas and has its own local palette.

**Comment by seanlinsley** [comment]
@nathanaeljones I'm interested in contributing to Imageflow and/or `image-gif` to polish up GIF support, but I could use quite a bit of guidance :)
