### ISSUE TITLE
Is there going to be a stand alone CLI tool?

### ISSUE THREAD

**Issue by dschissler** [imazen/imageflow#117]
I'm a kickstarter backer and I'm wondering if there is a Linux CLI tool that isn't a server?  I'd rather not clog up your issues with such a simple question but this seems to be the only place to ask the question.

**Comment by nathanaeljones** [comment]
Yes, there is - it's `imageflow_tool`, and you should be able to find it in the releases tab.

**Comment by nathanaeljones** [comment]
Would you prefer a docker image for it?

**Comment by dschissler** [comment]
No thats ok.
