### ISSUE TITLE
IIIF Image API Support?

### ISSUE THREAD

**Issue by jpstroop** [imazen/imageflow#118]
Imageflow looks great! I thought I'd bring [IIIF](http://iiif.io/) to your attention, and our [Image API Specification](http://iiif.io/api/image/2.1/) in particular, in case you've not seen it. Our community is always looking for new implementations and feedback on our specifications.

**Comment by jpstroop** [comment]
(To be clear, I thought this might be relevant to imageflow-server)

**Comment by nathanaeljones** [comment]
Thank you! 

Is there a related spec for access control, like AWS v4?

**Comment by jpstroop** [comment]
You bet! We do have an auth spec for access to images, but I think it occupies a different space: http://iiif.io/api/auth/1.0/

**Comment by lilith** [comment]
I'm not sure how relevant this will be since we don't support TIFF or JPEG2000. Some of the features we also don't plan to support very soon. I will keep this in mind but close for now.
