### ISSUE TITLE
Roadmap of Imageflow

### ISSUE THREAD

**Issue by CShepartd** [imazen/imageflow#122]
Hi,

I want to suggest to add roadmap of project to readme.md or docs. "Delivery Schedule" from Kickstarter is outdated and can be misunderstood

**Comment by nathanaeljones** [comment]
What questions would you like to have answered? We are still targeting the August 2017 deadline for a stable release of imageflow_server, libimageflow, Ruby, and Node bindings. 

The order of task completion until then is dependent on a lot of factors, including whether we can inspire backers to give us feedback, and how quickly our software dependencies mature.

**Comment by nathanaeljones** [comment]
Does the new README address your questions?

**Comment by CShepartd** [comment]
A bit cuz still missing milestones with dates (like here https://github.com/dotnet/core/blob/master/roadmap.md)

BTW Anyone care about Node wrapper?
