### ISSUE TITLE
Build failed (long path names)

### ISSUE THREAD

**Issue by batooo** [imazen/imageflow#126]
`
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\BatoPC\.conan\data\libjpeg-turbo\1.5.1\imazen\testing\build\9fa351ac1b30ceabd1b27310408605a456b5fd86\libjpeg-turbo-a964424b0195162b7aff6fb951aab5e3953c22d1\_build\CMakeFiles\3.8.0-rc3\CompilerIdCXX\CompilerIdCXX.vcxproj]

    0 Warning(s)
    1 Error(s)

Solution?
`

**Comment by nathanaeljones** [comment]
You might try a stable build of CMake like 2.7.x. It should remove 4 characters from the path, which may be enough. It's strange that the paths it lists are below the limits...

**Comment by batooo** [comment]
Couldn`t find 2.7 version in CMake archive, but after installing 3.7, build is ok.
With 3.8 i got above reported error.

**Comment by nathanaeljones** [comment]
3.7 is what I meant, sorry! Edited. Glad it worked.
