### ISSUE TITLE
'settings.target_cpu' doesn't exist

### ISSUE THREAD

**Issue by niklasalbin** [imazen/imageflow#129]
attempting to compile according to instructions, using Digital Ocean droplet ubuntu16 and docker ubuntu16, I'm getting the same error messages constantly:
ERROR: 'settings.target_cpu' doesn't exist
'settings' possible configurations are ['arch', 'build_type', 'compiler', 'os']

in the end I found this: 
https://github.com/conan-io/conan/issues/847

And I added the line suggested to .conan/settings.yaml

Maybe this should be in the Readme...

**Comment by nathanaeljones** [comment]
Fixed
