### ISSUE TITLE
Read Exif data

### ISSUE THREAD

**Issue by uasan** [imazen/imageflow#131]
Hi.

We used GraphicsMagick, for resize and getting metadata in STDOUT:
`gm convert big.jpg -format "%w %h %[exif:DateTime]" -write info:- -strip -resize "250x250>" small.jpg`

How to do this on `imageflow_tool`, where there is documentation?
Thank.

**Comment by nathanaeljones** [comment]
Imageflow doesn't yet implement metadata parsing (except what is required for correctly interpreting color and rotation). 

We'd rather not pull in an C or C++ library for this, as it would increase the attack surface area, so we'll likely wait until we can develop and fuzz and implementation in safe Rust code. 

Are you dealing with 100% trusted image files?
