### ISSUE TITLE
Image file size increase a lot

### ISSUE THREAD

**Issue by crysehillmes** [imazen/imageflow#133]
File: [http://ifanr-cdn.b0.upaiyun.com/wp-content/uploads/2017/07/MG_0415-1.jpg](http://ifanr-cdn.b0.upaiyun.com/wp-content/uploads/2017/07/MG_0415-1.jpg)
File Size: 1.60MB
File Size from imageflow_server: 15.1MB 

I also find some other jpg have this problem.

**Comment by nathanaeljones** [comment]
What quality value are you using? If it's higher than the original, then the size increase makes sense. We don't yet have auto encoder tuning implemented.

**Comment by crysehillmes** [comment]
I don't use any param here, so it's the default quality.

My server command: `.\imageflow_server.exe start --bind-address 0.0.0.0 --port 10505 --data-dir ../HostedData --mount "/images/:ir4_local:..\Hosted"`

Request URL: `http://localhost:10505/images/MG_0415-1.jpg`

**Comment by nathanaeljones** [comment]
Yes, it's much lower than the default (which is 90). http://localhost:10505/images/MG_0415-1.jpg?quality=30 might be more in line with size expectations. 

That said, we haven't optimized jpeg file sizes yet, so another 5-25% should be possible later in development.
