### ISSUE TITLE
imageflow_server with ir4_http mount always returns Error:UpstreamHyperError(Uri(RelativeUrlWithoutBase))

### ISSUE THREAD

**Issue by arendlagendijk** [imazen/imageflow#134]
Using imageflow_server with an ir4_http mount always results in an Internal Server Error.

```json
Internal Server Error
Info:"httpflowers.jpg"
Error:UpstreamHyperError(Uri(RelativeUrlWithoutBase))
```

Started imageflow_server with: `imageflow_server start --data-dir /tmp/imageflow_data --mount /extern/:ir_http:http:://images.unsplash.com/`

Requested URL: http://localhost:39876/extern/flowers.jpg

It seems that during parsing the mount argument is split on the ':', but the target server URL is never joined afterwards and only the protocol part is used while constructing the full target URL.

1. given mounts are parsed during server startup by `fn parse_mount(s: &str)`.
2. split by ':', resulting in a vector [“/extern/”, “ir4_http”, “http”, “”, “//images.unsplash.com”]
3. a MountLocation is created from the result `MountLocation::parse(“/extern/”, “ir_http”, [“http”, “”, “//images.unsplashed.com”])`
4. While setting up the MountEngine only the first element from the MountLocation engine_args is used
```rust
fn ir4_http_setup(mount: &MountLocation) -> Result<(String, EngineHandler<String>), String> {
    if mount.engine_args.len() < 1 {
        Err("ir4_http requires at least one argument - the base url to suffix paths to".to_owned())
    } else {
        Ok((mount.engine_args[0].to_owned(), ir4_http_handler))
    }
}
```

This results in a wrong remote server URL wherein the host part is omitted.

**Comment by nathanaeljones** [comment]
Thank you for reporting this. I'll investigate why the integration tests didn't catch this.

**Comment by arendlagendijk** [comment]
If the tests from imageflow_server/tests/test_ir4.rs are used for integration testing then this issue is missed.

The tests in test_ir4.rs are based on running imageflow_server in `--demo` mode. In demo mode, the vector assigned to engine_args of the Ir4Http MountLocation has the full remote server URL as first element.

```rust
let mut mounts = vec![
            MountLocation {
                engine: MountedEngine::Ir4Http,
                prefix: "/ir4/proxy_unsplash/".to_owned(),
                engine_args: vec!["http://images.unsplash.com/".to_owned()]
            },

            ...
];
```
That's a valid case, but different from the vector passed from the parsed mount command line argument.

If above is true, then `fn parse_mount(s: &str)` is not used for creating the MountLocation during integration testing.
