### ISSUE TITLE
error: Could not compile `syntex_syntax`.

### ISSUE THREAD

**Issue by edugonch** [imazen/imageflow#140]
Hello, I'm making a clean installation on Ubuntu 17.04, I'm following the  instructions on this site and the docker file.
But when I run ./build.sh I get this error (I don't know where to add the --verbose param, build.sh is not accepting that)

   Compiling url v1.4.1
   Compiling serde_derive_internals v0.15.1
   Compiling openssl v0.9.13
   Compiling openssl-sys v0.9.13
   Compiling regex v0.2.2
   Compiling syntex_syntax v0.58.1
error: Could not compile `syntex_syntax`.

To learn more, run the command again with --verbose.

**Comment by nathanaeljones** [comment]
What version of rust are you using?

**Comment by edugonch** [comment]
rustc 1.19.0-nightly (e2eaef849 2017-06-11)

**Comment by nathanaeljones** [comment]
Try running `cargo build --all --verbose`. And maybe try rust 2017-08-01

**Comment by edugonch** [comment]
It didn't give me any error (I think)

https://gist.github.com/edugonch/f3473cff092177c77e176d9fddd9f5ec

**Comment by nathanaeljones** [comment]
... huh. Maybe because build.sh uses CARGO_INCREMENTAL=1 and your nightly hit a weak spot between the ever-breaking syntex_syntax crate and that? If you can reproduce it, it might be worth a bug report. 

You have successfully compiled Imageflow, on the plus side.

**Comment by pornel** [comment]
If you were compiling in a small VM, it could have ran out of memory (`syntex_syntax` crate is pretty big, and other compilations done in parallel could have increased memory pressure).

**Comment by edugonch** [comment]
Yes, it can be, I'm making the test in a $10 Digital Ocean VM.

**Comment by edugonch** [comment]
I just update the droplet to a $40 (2 CPU, 4GB Ram) and it is compiling everything,

Thanks guys for the help.
