### ISSUE TITLE
Unrecognized leading byte sequence

### ISSUE THREAD

**Issue by edugonch** [imazen/imageflow#143]
Hello, I got this error while processing one image

`Internal Server Error
Info:"/media/images/51f756cf-1556-4bac-af19-2a56131c2587-21083198_1425746450812456_3985007399136053101_o.jpg"
Error:BuildFailure(Error { httpish_code: 500, message: "Err(FlowErr { code: 40, message_and_stack: \"Not implemented : Unrecognized leading byte sequence ffd8ffe20bf84943\\ncodecs.c:206: in function flow_codec_select_from_seekable_io\\n\" })" })`

This is the image https://ibb.co/mc2a9Q

**Comment by nathanaeljones** [comment]
Thanks! This will be fixed in the next release. We were being too picky about magic bytes.

**Comment by nathanaeljones** [comment]
Fixed in v1.0.0-rc5a

**Comment by edugonch** [comment]
Thank you :)
