### ISSUE TITLE
error on image with 32bpc

### ISSUE THREAD

**Issue by token97** [imazen/imageflow#144]
Hey,
First of all, I want to say thank for imageflow, it's a very good tool.

But it seems imageflow don't read correctly some images generated from photoshop. When I try to get an image with 32bpc, imageflow crash and display the following error "Unsupported color conversion request". 

is planned to manage them?

**Comment by nathanaeljones** [comment]
See https://github.com/imazen/imageflow/issues/98  - We're actively looking for people to share images that don't work. 

Please upload your image (as small as possible) so that we can work to support it (assuming that is is a valid image).

**Comment by nathanaeljones** [comment]
The jpeg you uploaded is not a standard-compliant JPEG; it is a CMYK jpeg.  We'll keep the file in case we decide to eventually support CMYK jpegs. Thank you!

More information can be found here: https://graphicdesign.stackexchange.com/questions/50464/created-a-poster-to-print-in-cmyk-but-when-client-downloads-jpg-on-the-screen
