### ISSUE TITLE
ConanException: Error 256 while executing cmake "/www/imageflow/c_components"

### ISSUE THREAD

**Issue by pornel** [imazen/imageflow#145]
I'm getting a build error. I've got Xcode 9 on High Sierra.

> -- Conan: called by CMake conan helper
CMake Error at build/conanbuildinfo.cmake:568 (message):
  Incorrect 'apple-clang' version 'compiler.version=8.0' is not the one
  detected by CMake: 'Clang=9.0'
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:611 (conan_error_compiler_version)
  build/conanbuildinfo.cmake:662 (check_compiler_version)
  build/conanbuildinfo.cmake:409 (conan_check_compiler)
  CMakeLists.txt:12 (conan_basic_setup)

Looks like it's this error:

https://github.com/conan-io/conan/issues/1778

**Comment by nathanaeljones** [comment]
I just installed High Sierra on my mac this morning. I'll try to reproduce it. 

You can likely just edit https://github.com/imazen/imageflow/blob/master/c_components/CMakeLists.txt#L4 as a workaround, assuming it's the same error.

**Comment by memsharded** [comment]
The https://github.com/conan-io/conan/issues/1778 seems not related, it was the user used an outdated conanbuildinfo.cmake.

Have you updated your conan client? Which version are you running? Also, it is very important to make sure that you installed your dependencies for the same version you are now compiling. What is in your default profile?

**Comment by nathanaeljones** [comment]
I wasn't able to reproduce it. I reformatted my drive last night so it's a pretty clean machine. 

My known good `~/.conan/profile/default` file contained

```
[build_requires]
[settings]
os=Macos
arch=x86_64
compiler=apple-clang
compiler.version=9.0
compiler.libcxx=libc++
build_type=Release
[options]
[scopes]
[env]
```

**Comment by pornel** [comment]
Thanks. The profile fixed my issue.
