### ISSUE TITLE
test_encode_*_smoke fail due to PROFILE_TRANSFORMS duplicate inserts

### ISSUE THREAD

**Issue by pornel** [imazen/imageflow#147]
> thread 'test_encode_gif_smoke' panicked at 'Hash table contains already key, contrary to the assumptions about `insert_new`'s arguments.'

Backtrace leads to:

```rust
if !PROFILE_TRANSFORMS.contains_key(&hash) {
                        let transform = ColorTransformCache::create_profile_transform(color, pixel_format).map_err(|e| e.at(here!()))?;
                        PROFILE_TRANSFORMS.insert_new(hash, transform);
                    }
```

I'm running `cargo test --all` on a Mac.

**Comment by nathanaeljones** [comment]
I missed this due to RUST_TEST_THREADS=1, which is needed for dealing with the checksums file. Thank you!
