### ISSUE TITLE
Server test assumes GIT_COMMIT (=HEAD) is on GitHub

### ISSUE THREAD

**Issue by kornelski** [imazen/imageflow#151]
> 	thread 'run_server_test_i4' panicked at 'UpstreamResponseErrorWithResponse { status: NotFound, response: FetchedResponse { content_type: ContentType(Mime(Text, Plain, [])), length: 188, as_string: Ok("Remote file not found (upstream server responded with 404 to \"https://raw.githubusercontent.com/imazen/imageflow/71bbea03e17bc8222cac428e7742f5b9a7d357f8/imageflow_server/demo/index.html\")") } } for http://localhost:57399/proxied_demo/index.html', imageflow_server/tests/test_ir4.rs:241:28

The hash comes from `GIT_COMMIT`, which comes from build.sh setting it from `HEAD`. So if `HEAD` is not pushed to github, the download fails. That gets in the way of testing of local branches.

**Comment by nathanaeljones** [comment]
Thanks! Yeah, I hadn't gotten around to fixing this yet.

**Comment by lilith** [comment]
Thanks again for fixing this.
