### ISSUE TITLE
Sharpening doesn't seem to work as expected

### ISSUE THREAD

**Issue by jedisct1** [imazen/imageflow#159]
Using the current Docker image, sharpening seems to have a pretty weird behavior.

`a.sharpen` and `s.sharpen` don't do anything. Only `f.sharpen` does.

But `f.sharpen` doesn't seem to sharpen much until `f.shapen=3`. Starting at `3`, the whole image immediately becomes overexposed.

Attached is a sample image I tried to resize and sharpen with:

```sh
imageflow_tool v0.1/ir4 --in /tmp/tof-12705.jpg --out /tmp/thumb.jpg --command "width=1080&f.sharpen=3"
```

![tof-12705](https://user-images.githubusercontent.com/124872/32914970-a653bbc4-cb17-11e7-99bc-9067c3fce186.jpg)

And the outcome:

![thumb](https://user-images.githubusercontent.com/124872/32915017-cc973ec8-cb17-11e7-9ec8-0fbbfc41eeda.jpg)

Is it the expected behavior?

**Comment by nathanaeljones** [comment]
Nope, not expected. cause: 1 character typo :(

**Comment by nathanaeljones** [comment]
It looks like this did not fix all instances of this problem.
