### ISSUE TITLE
Tracking issue for nightly-only features

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#161]
### imageflow_abi

```
#![feature(core_intrinsics)]
fn type_name_of<T>(_: T) -> &'static str {
    extern crate core;
    unsafe { core::intrinsics::type_name::<T>() }
}
```
### imageflow_core
```
#![feature(concat_idents)]
#![feature(oom)]
#![feature(conservative_impl_trait)]
#![feature(proc_macro)]
#![feature(integer_atomics)]
#![feature(as_c_str)]
#![feature(core_intrinsics)]
#![feature(fn_must_use)]
```
### imageflow_helpers

```
#![feature(global_allocator, allocator_api, heap_api)]

#![feature(integer_atomics)]
#![feature(ascii_ctype)]
#![feature(i128_type)] // Not used heavily, removable
```

### imageflow_server

```
#![feature(proc_macro)]
#![feature(integer_atomics)]
#![feature(conservative_impl_trait)]

```

### imageflow_tool
```
#![feature(slice_concat_ext)]
```

**Comment by nathanaeljones** [comment]
`#![feature(global_allocator, allocator_api, heap_api)]` are required for valgrind use. 

I don't know how to write good concurrent structures without integer atomics anymore. 

These are also used pretty heavily: 

```
#![feature(conservative_impl_trait)]
#![feature(proc_macro)]
```

**Comment by nathanaeljones** [comment]
It looks like `#![feature(concat_idents)]` has a stable user-land alternative and may be phased out.

**Comment by nathanaeljones** [comment]
When the system allocator becomes default, we won't need `#![feature(global_allocator, allocator_api, heap_api)]`.. but then, those will become stable first as a prerequisite.

**Comment by kornelski** [comment]
Here's my attempt on stable: https://github.com/imazen/imageflow/commit/a700c260191999052ab23d28faf1ccd27c71fb55

They're not proper fixes, just to get it to compile.

**Comment by nathanaeljones** [comment]
Still too early imho

**Comment by nathanaeljones** [comment]
@kornelski  You eliminated all nightly features, right? (core_intrinsics is only used for better error messages when aborting the process when a null context pointer is provided to the C API).

**Comment by kornelski** [comment]
Yes, it's done!
