### ISSUE TITLE
Add io::Error to FlowError conversion

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#164]

**Comment by nathanaeljones** [comment]
cc: @pornel 

At the ErrorCategory level, I current distinguish between:

* `::ImageMalformed` category - The decoder failed because the data stream is bad. Includes `ErrorKind::GifDecodingError` and `ErrorKind::ColorProfileError`
* `::IoError`, which includes `EncodingIoError` -  (presumably write failure) and `::DecodingIoError` - (presumably read failure). 
* `::InternalError` - Bugs; including where a codec has triggered `std::io::ErrorKind::InvalidInput`. These currently all have separate ErrorKind:: enumerations, but I'm not sure it's necessary. InternalError should be sufficient if the error message contains the decoder name.

The debug representation of the original ::std::io::Error should always be preserved.

I think an automated cast would only make sense if we merge EncodingIoError and DecodingIoError. I think it's useful to tell them apart, and that maybe they should even be separate in ErrorCategory. What are your thoughts?

**Comment by pornel** [comment]
OK, I can use `EncodingIoError`

**Comment by nathanaeljones** [comment]
Here's an example helper: 

```
    pub fn from_lodepng_encoder(e: ::std::io::Error) -> Self{
        // Bad usage of I/O interface
        if e.kind() == ::std::io::ErrorKind::InvalidInput{
            FlowError::without_location(ErrorKind::LodepngEncodingError, format!("{:?}", e))
        }else{
            FlowError::without_location(ErrorKind::EncodingIoError, format!("{:?}", e))
        }

    }
```
