### ISSUE TITLE
Checksums make DSSIM test impossible to fail

### ISSUE THREAD

**Issue by pornel** [imazen/imageflow#165]
`POPULATE_CHECKSUMS` stores checksum of the result — as if it was correct — before running DSSIM. This means that even if DSSIM rejects the result, it will be remembered as correct anyway and DSSIM won't be run again.

**Comment by nathanaeljones** [comment]
It's not supposed to have an effect unless there's no stored checksum.

**Comment by pornel** [comment]
I've pushed a fix to master that allows dssim to run if there is no stored checksum. Previously it never even reached DSSIM, because "no stored checksum" was reported as "matches exact == true"

**Comment by pornel** [comment]
But this is still not enough:

Run 1:

1. No stored checksum, store now
2. Run DSSIM
3. DSSIM failure, test fails

Run 2:

1. There is stored checksum
2. The end; test passes

**Comment by nathanaeljones** [comment]
Fixed; there is now compare_encoded_against_source
