### ISSUE TITLE
Incompatibility with latest conan

### ISSUE THREAD

**Issue by kornelski** [imazen/imageflow#168]
> conan install: error: unrecognized arguments: --scope --scope debug_build=False --scope coverage=False --scope skip_test_run=False ../
ERROR: Exiting with code: 2

That's because:

http://docs.conan.io/en/latest/changelog.html?highlight=scopes

> ### Breaking changes
>   * scopes have been completely removed. You can use environment variables, or the conanfile.develop or conanfile.in_local_cache attributes instead.

The version 0.30 is now in homebrew, so imageflow doesn't build on macOS.

**Comment by pornel** [comment]
Workaround for homebrew:

```sh
brew uninstall --force conan
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
git checkout 971a4ec25f6835874379a2850d8c5fedc4690746 conan.rb
brew install conan
```

**Comment by nathanaeljones** [comment]
Thanks. I haven't had time to redo the Conanfiles... it's been about a year.

**Comment by nathanaeljones** [comment]
I'll try to have someone get them updated. Are we close to making CI green again?

**Comment by memsharded** [comment]
Hi all.

Indeed the scopes were very old, much before we had env-vars, and package env-vars, as well as other mechanisms as ``self.develop`` attribute. They haven't been in the conan docs for months now. Sorry for breaking this, but we are preparing conan 1.0 and it was time to deprecate and remove some debt.
Please ask if you need help updating the conanfiles, shouldn't be difficult. Thanks!
