### ISSUE TITLE
Set MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by pornel** [imazen/imageflow#170]
Travis.yml has a comment:

>     #Should be compatible with El Capitan forward. xcode8

Instead of using an older macOS version as the host, the build script should probably set:

```sh
export MACOSX_DEPLOYMENT_TARGET=10.11
```

to make Apple's compilers and linkers produce compatible output. Although I haven't tested whether it matters for 10.11, that setting was definitely needed for 10.7 backwards compat due to mach-o header changes in later macOS versions.

**Comment by nathanaeljones** [comment]
Thanks!  You're right.
