### ISSUE TITLE
engine documentation, caching, basic setup

### ISSUE THREAD

**Issue by urbanhop** [imazen/imageflow#176]
Looks like the very best image resizing OSS. Thx for sharing all your knowledge about the topic. Just tried it and wondered:

1. Is there a description of engines?

2. I managed to set it up, such that it transforms, but it does not cache (windows):
imageflow_server.exe start --mount "/img/:ir4_local:.\fotos" --data-dir "m:/cache" --port 4444
Is it possible to cache the transformations?

3. When I use the peracache_proxy engine:
imageflow_server.exe start --mount "/img/:permacache_proxy:.\fotos" --data-dir "m:/cachy" --port 4444
the http request 
http://localhost:4444/img/102.jpg?width=200
returns
Internal Server Error
Info:".\\fotos102.jpgwidth=200"
Error:UpstreamHyperError(Uri(RelativeUrlWithoutBase))

**Comment by nathanaeljones** [comment]
1. Just what imageflow_server --help shows you.
2. You can use ARR on Windows. Given that nginx and IIS now offer disk caching, and that you want to put them in front of any http app anyway, it's not a big priority yet.
3. Forward slashes the only type of slashes used in urls - backslashes are problematic.

**Comment by urbanhop** [comment]
all clarified, thx so much + for the project!
