### ISSUE TITLE
libimageflow.so missing from publish

### ISSUE THREAD

**Issue by mcm-ham** [imazen/imageflow#177]
Just trying out imageflow on an ASP.NET Core 2 test project and finding that if I install Imageflow.NativeRuntime.ubuntu_14_04-x86_64 nuget package I see no libimageflow.so in build output and when I publish and run on a ubuntu docker image I get an error about that file is missing.

**Comment by nathanaeljones** [comment]
This issue would belong at https://github.com/imazen/imageflow-dotnet/issues

Are you sure you're on Ubuntu 14.04 x86_64? try `lsb_release -a` and `uname -a` to get that info.

**Comment by mcm-ham** [comment]
```
This issue would belong at https://github.com/imazen/imageflow-dotnet/issues
```
Makes sense, sorry for that if this is a legitimate issue it can be moved there.
```
Are you sure you're on Ubuntu 14.04 x86_64? try lsb_release -a and uname -a to get that info.
```
I believe I'm using Ubuntu 18.04 x86_64, the docker image I'm using is `microsoft/dotnet:2.1-sdk-bionic` for the build and `microsoft/dotnet:2.1-runtime-deps-bionic` for the actual deployment. `lsb_release -a` command doesn't exist but `uname -a` output:
```
Linux b3162e04be84 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
The issue seems to be what version I specify when publishing the app, if I change to this it works:
```
dotnet publish -c Release -o out -r ubuntu.14.04-x64
```
Now it publishes the missing file and resizing of images are working correctly.

I could target ubuntu.16.04 instead but do I now need to spend effort each time I run the app on the server to find out the CPU architecture whether it's Haswell or Sandybridge? For example I'm planning to try this out on Digital Ocean which would be a virtual CPU does that matter or does it just depend on what the host CPU is? What if the CPU is later like Broadwell or Skylake? Do I need that specific version of Ubuntu or running a later version like 18.04 is ok?

**Comment by nathanaeljones** [comment]
The Haswell/sandybridge/etc packages rely on the instruction sets supported by those and later platforms. YMMV running them on AMD, but I'd be surprised if they didn't work just fine. 

Haswell has (for me) been a safe bet on all cloud providers. Very few CPUs older than that generation are still running in commercial clouds.

YMMV using older ubuntu binaries on newer releases, but generally it works. I plan to add an 18.04 package when I can.
