### ISSUE TITLE
Rust version in Docker

### ISSUE THREAD

**Issue by kornelski** [imazen/imageflow#179]
Rust in Docker is an older version. 

I've [worked around it](https://github.com/imazen/imageflow/blob/master/.travis.yml#L24), but it'd be faster if the upstream image was updated, since it looks like there's no caching at all in Travis when docker is used.

BTW, also add `cargo install sccache` in the docker image.

**Comment by nathanaeljones** [comment]
All docker images have been updated to 2018-05-15
