### ISSUE TITLE
ir4_http is not working with firebase storage

### ISSUE THREAD

**Issue by danconte72** [imazen/imageflow#185]
### Scenario
- I was mounting images sources and it worked correctly on a regular files CDN;
- But I need to do this with a firebase storage too. 
- Download URLs on [firebase storage](https://firebase.google.com/docs/storage/) demands ***?alt=media*** after file path, 
as you can check in this sample:
[https://firebasestorage.googleapis.com/v0/b/solid-antler-163519.appspot.com/o/image.jpg?alt=media](https://firebasestorage.googleapis.com/v0/b/solid-antler-163519.appspot.com/o/image.jpg?alt=media)
- If  ***?alt=media*** is removed, firebase only returns metadata:
[https://firebasestorage.googleapis.com/v0/b/solid-antler-163519.appspot.com/o/image.jpg](https://firebasestorage.googleapis.com/v0/b/solid-antler-163519.appspot.com/o/image.jpg)

### Problem
- Looks like that ir4_http image are not sending the required param do remote source;
- I already tried scape chars on my requests to imageflow_server but it not worked;

### Questions
- Is there a way to force add this param when mount an image source?
- Is there a way to pass this param though request to imageflow_server?

**Comment by nathanaeljones** [comment]
There's not currently a way to do this, but I plan to add a new engine type that would allow you to encode the remote URLs in such a way that they can include querystrings.

**Comment by Dock1100** [comment]
> There's not currently a way to do this, but I plan to add a new engine type that would allow you to encode the remote URLs in such a way that they can include querystrings.

Hi lilith, any progress on it?

**Comment by danconte72** [comment]
> > There's not currently a way to do this, but I plan to add a new engine type that would allow you to encode the remote URLs in such a way that they can include querystrings.
> 
> Hi lilith, any progress on it?

Hey :) We done using [firebase links](https://firebase.google.com/docs/dynamic-links/rest).
- upload the image to firebase
- get the url and create a dynamic link using firebase links
- passing  dynamic link of image to imageflow + imageflow params. Something like `my.dynamic.page.link/F5sf?width=169&height=169&mode=crop&scale=both`
- it worked for us so far

**Comment by lilith** [comment]
Great! I'll close this issue (but we'll still add remote URL support in a future version)
