### ISSUE TITLE
TodayILearned - Running imageflow_server in Azure Web App

### ISSUE THREAD

**Issue by jakenuts** [imazen/imageflow#186]
It might be a bit early, or a back-assward way to use imageflow_server, but I tried setting it up in an Azure Web App (Windows) using httpplatformhandler to launch & forward requests and it seemed to work quite well.

1.) Connect to the new web app with FTP and open the wwwroot folder
2.) Create a App_Data folder for the cache
3.) Copy this web.config & imageflow_server.exe (and possibly the dll)  to wwwroot

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <remove name="httpplatformhandler" />
            <add name="httpplatformhandler"
                path="*"
                verb="*"
                modules="httpPlatformHandler"
                resourceType="Unspecified" />
        </handlers>
        <httpPlatform processPath="./imageflow_server.exe"
            arguments="start --bind-address 127.0.0.1 --port %HTTP_PLATFORM_PORT% --data-dir ./App_Data --mount &quot;/myblobs/:ir4_http:https:://myblobs.blob.core.windows.net/assets/&quot;"
            stdoutLogEnabled="true"
            stdoutLogFile="./imageflowiis.log"
            startupTimeLimit="20"
            requestTimeout="00:05:00">
        </httpPlatform>
    </system.webServer>
</configuration>`

Cheers!

**Comment by JamoCA** [comment]
I'm using a locally hosted IIS server and haven't used httpplatformhandler before.  )httpplatformhandler was an extra component that I had to download & install.)  More info here:
https://azure.microsoft.com/en-us/blog/announcing-the-release-of-the-httpplatformhandler-module-for-iis-8

Where's the best information regarding doing this?  I'd like to be able to support multiple websites/mounts and not sure if I'm required to set up a unique hostname for each or not.

**Comment by JamoCA** [comment]
Have you attempted to use IIS to reverse proxy the imageflow server?

Here's a quick how-to article:
https://blog.ligos.net/2016-11-14/Reverse-Proxy-With-IIS-And-Lets-Encrypt.html

**Comment by jessegavin** [comment]
@jakenuts I tried this out and it seems to work great! Thanks for sharing.
