### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by jbboehr** [imazen/imageflow#187]
Does imageflow_server have a health endpoint?

**Comment by nathanaeljones** [comment]
Not yet. What information would you like/expect it to expose?

**Comment by jbboehr** [comment]
Well, the most basic would just be an endpoint that returns 200 if the node has booted.

I'm using it with haproxy and consul. For haproxy, I set the health check to expect a 404 at the root. For the consul health check, it doesn't support custom status codes, so I set it to expect something listening on tcp at the desired port.

**Comment by cassiussa** [comment]
What I did was `--mount /health-check/:ir4_local:./health/` and placed a tiny image file in the `./health/` directory.  Then I tested against it... `GET /health-check/healthy.jpg`

Would that work for you too?

**Comment by lilith** [comment]
Imageflow.NET Server has /imageflow.health and /imageflow.ready endpoints.

imageflow_server is obsolete: https://github.com/imazen/imageflow/issues/598
