### ISSUE TITLE
If a mounted UNC path is unavailable during server start, the server will not start

### ISSUE THREAD

**Issue by JamoCA** [imazen/imageflow#189]
We had an issue where we took a server offline and a mounted UNC path became unavailable.  After restarting the ImageFlow server, we received nothing but 500 errors until we removed the non-existent path from the startup command line.

Just curious, if we would have used HTTP to mount path and the website didn't exist, would it encounter the same start-up issue or is this only with UNC paths.

**Comment by lilith** [comment]
@JamoCA Closing due to no response.
