### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by ishitatsuyuki** [imazen/imageflow#193]
While SVG has been supported in more browsers than those support imgset, there are some corner cases where rasterized images are required.

The cases I know are:
- Open Graph Protocol (social media cards)
- Favicons (Only Firefox supports SVG directly)

For the implementation, [resvg](https://github.com/RazrFalcon/resvg) seems to be a good candidate.

**Comment by lilith** [comment]
resvg still requires a Qt or Cairo backend. This would have to be a plugin, and is probably better suited to execute in a container.

**Comment by lilith** [comment]
I'm going to close this one for now, as I don't anticipate working on it in the next year or two.
