### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by ishitatsuyuki** [imazen/imageflow#194]
While WebP is only supported by Chrome, its dominance of market means that about 70% of the users will able to load that format.

WebP is a good compromise between JPEG and PNG, in terms that it can perform lossy compression while not destroying alpha properties. It simply compresses better, too.

**Comment by polarathene** [comment]
Firefox released version 65 early 2019, now providing WebP support too.

**Comment by teacoat** [comment]
Agreed, browser support is good enough and the benefits plenty, please support!

**Comment by lilith** [comment]
libwebp is 1.0 now, so we can support it.

**Comment by kepi** [comment]
Are there any news about WebP support?

**Comment by lilith** [comment]
Not yet, although we had a big breakthrough today that should free up more dev effort towards webp and rewriting the webserver.

**Comment by kornelski** [comment]
I'm maintaining bindings if you need them: https://lib.rs/crates/libwebp-sys

**Comment by lilith** [comment]
@kornelski Perfect! I'll use those. Do you have any suggestions for output tuning or presets? The array of options seems dizzying.

**Comment by kornelski** [comment]
I haven't looked into tuning these options yet.

**Comment by lilith** [comment]
Thanks! I've just used the simple encoder API for now. 

WebP support can be activated using the webplossy {quality} and webplossless encoder presets or using &format=webp&quality=x or &format=webp respectively. 

This is in master.

**Comment by lilith** [comment]
Update: you now use &webp.lossless=true|false and &webp.quality=0..100 to adjust compression rather than reusing the jpeg quality command.
