### ISSUE TITLE
Publishing to docker

### ISSUE THREAD

**Issue by stijnsta** [imazen/imageflow#196]
When we publish in docker we get the following error:
```
System.DllNotFoundException: Using "lib[basename].so" Subdir="x64", IsUnix=True, IsDotNetCore=False
Before searching: Unable to load shared library 'imageflow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libimageflow: cannot open shared object file: No such file or directory
Error Success loading imageflow from /app/x64/libimageflow.so
Error Success loading imageflow from /app/libimageflow.so
Error Success loading imageflow from /app/x64/libimageflow.so
Error Success loading imageflow from /app/libimageflow.so
   at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflow_abi_ver_major, UInt32 imageflow_abi_ver_minor)
   at Imageflow.Bindings.JobContextHandle.<>c.<.ctor>b__0_0()
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)

   at Imageflow.Bindings.NativeLibraryLoader.LoadLogger.RaiseException()
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
   at Imageflow.Bindings.JobContextHandle..ctor()
   at Imageflow.Bindings.JobContext..ctor()
```

On windows, it works fine. 
On linux not:
The so files are present in that directory. Any idea what we are doing wrong?

Stijn

**Comment by stijnsta** [comment]
![image](https://user-images.githubusercontent.com/39943542/46343307-a9455c80-c63d-11e8-95d5-4a22fcef35c9.png)

**Comment by lilith** [comment]
What does your dockerfile look like?

**Comment by stijnsta** [comment]
`FROM microsoft/dotnet:2.1.1-aspnetcore-runtime

RUN apt-get update \
    && apt-get install -y --no-install-recommends libc6-dev
RUN apt-get update \
	&& apt-get install -y --no-install-recommends openssl
WORKDIR /app
COPY /bin/release/netcoreapp2.1/ubuntu.16.04-x64/publish .
WORKDIR /
COPY /bin/release/netcoreapp2.1/ubuntu.16.04-x64/publish/*.so /lib/x86_64-linux-gnu/

WORKDIR /app

ENTRYPOINT LD_DEBUG=files dotnet Imageresizercore_v2.dll`

First I didn't copy the *.so files to the lib, but it didn't work, so now I copy them, but it still doesn't work.

**Comment by lilith** [comment]
Looking at the error message, it expects them to be with the app, not in /lib
```
Error Success loading imageflow from /app/x64/libimageflow.so
Error Success loading imageflow from /app/libimageflow.so
Error Success loading imageflow from /app/x64/libimageflow.so
Error Success loading imageflow from /app/libimageflow.so

```

**Comment by stijnsta** [comment]
The *.so files are in the /lib and in the /app folder. I copied them to /lib just to be sure. But it indeed doesn't seem necessary. 

So they are built for ubuntu 16.04, which ones should we use for use in docker then?

**Comment by lilith** [comment]
See https://github.com/imazen/imageflow/issues/212

Microsoft now has Ubuntu docker images you can use.

Try mcr.microsoft.com/dotnet/core/sdk:2.2-bionic per https://hub.docker.com/_/microsoft-dotnet-core-sdk/
