### ISSUE TITLE
How to get logs

### ISSUE THREAD

**Issue by cassiussa** [imazen/imageflow#198]
The documentation suggests that logs should show up in the folder specified by the `--data-dir` flag.  However no logs are appearing in that folder.  They also don't appear to show up in `/var/log/` anywhere either.

How do we see what URLs are being requested from imageflow server?

Not sure if it makes any difference, but we're using the `ir4_proxy_uncached` option.

**Comment by lilith** [comment]
Logging to disk isn't implemented yet, currently everything goes to STDERR/STDOUT.

**Comment by cassiussa** [comment]
Thanks Lilith.  Love the name btw ;)  It's no problem for us if it doesn't go to disk, but we're also not seeing it appear in STDOUT either.  I do see a few things showing up in STDERR however.

I'll try installing a newer version...  v1.1.0-rc16 is named "(testing)".  Should we avoid that and go with v1.1.0-rc15?  Not sure if rc15 has the `ir4_proxy_uncached` parameter.

**Comment by lilith** [comment]
Newer releases should be better. But logging is still not implemented, as there is a pending rewrite of the image server against a newer framework.

**Comment by lilith** [comment]
imageflow_server is obsolete https://github.com/imazen/imageflow/issues/598
