### ISSUE TITLE
www.imageflow.io uses a self-signed certificate

### ISSUE THREAD

**Issue by chrsoo** [imazen/imageflow#199]
The official site [www.imageflow.io](https://www.imageflow.io/) uses a self-signed certificate and is thus blocked by many corporate policies.

Please use a certificate signed by [Let's Encrypt](https://letsencrypt.org/) or another well-known CA!

**Comment by kornelski** [comment]
It works for me with Comodo certificate. Something may be attacking your network?

**Comment by chrsoo** [comment]
This is really weird:

* I see the Comodo-signed certificate from home using a non-corporate computer
* First I also saw the Comodo-signed certificate from my corporate workstation over our company VPN
* Then it stopped working and I again see the self-signed certificate (which is blocked)

Possible explanations:
1. The corporate proxy acts as a man-in-the-middle and replaces the certificate
1. A misconfigured imageflow.io server serves pages using a self-signed certificate but other web servers use the Comodo certificate
1. There is a real man in the middle and our network/my workstation is compromised

The first case seems improbable as I don't see why the real certificate would be replaced by a self-signed certificate by our proxy.

The second would imply that other would have the same problem (if anybody has seen the issue, please say so!)

The third option... well, that is quite disturbing and feels highly improbable, but... if the first two explanations are falsified... well, I can't think of another option.

I will check internally and get back as soon as possible.

**Comment by chrsoo** [comment]
Well, it turns our security team are replacing certificates for sites that are not white listed.

By accessing the site directly over https instead of http I did not end up in the correct error page that allows me to request white listing of the site.

So the problem is entirely on our side, sorry!

Closing the issue.

**Comment by chrsoo** [comment]
Well, it turns our security team are replacing certificates for sites that are not white listed.

By accessing the site directly over https instead of http I did not end up in the correct error page that allows me to request white listing of the site.

So the problem is entirely on our side, sorry!

Closing the issue.
