### ISSUE TITLE
Optimize images for web

### ISSUE THREAD

**Issue by kepi** [imazen/imageflow#200]
I'm trying to use imageflow for serving images through imageflow server with `ir4_local` engine.

It is working great so far, but I failed to find any information about possibility to "optimize images for web", remove metadata etc. It would be great to be able to achieve smaller size as if I use _pngcrush_, _jpegoptim_ or similar software.

If there is such option and I only failed to find it, let me know. I tried to go trough all commands in http://imageresizing.net/docs/v4/reference and gone trough readme couple times.

**Comment by kornelski** [comment]
There's no option to enable optimization, because it's always on :) Images are optimized for the web out of the box. All metadata is removed.
