### ISSUE TITLE
What's meaning this comment when typed './build.sh --install'

### ISSUE THREAD

**Issue by magichim** [imazen/imageflow#201]
Hi, I'm a imageflow newbie.

It might be a pool question, sorry. :)

I followed readme install instructions, but after I typed ./build.sh -release and when I types ./build.sh --install

I got a message like below it.
```
Applying IMAGEFLOW_BUILD_OVERRIDE install
Installed libimageflow, imageflow_tool, and imageflow_server
```
It doesn't looks like a error message, but I don't understand meaning.

What is exactly this meaning?

My environment
OS: mac os high sierra
rustc version: 1.29.2 (17a9dc751 2018-10-05)

please help me.

**Comment by lilith** [comment]
It means it installed the tools to your system. You should now be able to type `imageflow_tool --help`

**Comment by magichim** [comment]
@lilith  thanks!
