### ISSUE TITLE
Fix CMYK jpeg bug

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#203]
See inactive failing test here: https://github.com/imazen/imageflow/blob/df49f42b22d67b21568d8a018610772b5b40a428/imageflow_core/tests/visuals.rs#L387

**Comment by danieljuhl** [comment]
@lilith is this related to the underlaying issue mentioned in #188

**Comment by lilith** [comment]
Yes.

**Comment by danieljuhl** [comment]
Any news on this? Anything I / we can do to make imageflow compatible with CMYK jpeg?

**Comment by danieljuhl** [comment]
Or at least avoid that imageflow server crashes on CMYK images.

**Comment by lilith** [comment]
It requires a whole new jpeg codec API (TurboJpeg) and adapter. Not an easy
fix.

**Comment by danieljuhl** [comment]
How about catching the error, so the server does not crash on CMYK images? Is that an easier fix? :)

**Comment by kornelski** [comment]
I think it's already trying to catch the error, it's just that catching doesn't work due to https://github.com/rust-lang/rfcs/pull/2699

**Comment by lilith** [comment]
Turns out that setjmp was simply too late, it needed to be earlier. CMYK jpegs aren't supported but this is no longer a fatal error.
