### ISSUE TITLE
Cache Management

### ISSUE THREAD

**Issue by danconte72** [imazen/imageflow#204]
I was looking the docs and didn't understand how de cache works.

- how can I set the size limit?
- which cache strategy has been used (FIFO, LRU...)? Can I change this? How?
- how to clean/reset the cache for a specific file?

**Comment by lilith** [comment]
The "cache" is just for demo purposes. At the moment, you would want to use your web server's disk cache for production use. Both IIS and NGINX offer one.

**Comment by danconte72** [comment]
Thanks
