### ISSUE TITLE
Low quality (fuzzy image) with specific resized image

### ISSUE THREAD

**Issue by kepi** [imazen/imageflow#205]
I'm resizing attached image (file `orig.jpg`) to width 565 using **ir4** in `imageflow_tool` or `imageflow_server`.

Resulting image doesn't look right, it is not sharp.

What I tried:

- versions 1.1.0-rc18, 1.0.0-rc14, 1.0.0-rc13 - all same behavior - file `test.if.jpg`
- adding `quality=100` - no or almost no change - file `test.if.100.jpg`
- converting orig to png and resize to png - same problem
- resize with imagemagick's convert (attached in test.im.jpg) - expected result, sharp image - file `test.im.jpg`

Is there any workaround I can try? Am I doing something wrong?

Full command:

```
❯ ~/apps/imageflow/imageflow_tool v0.1/ir4 --command "w=585" --in orig.jpg --out test.if.jpg
{
  "code": 200,
  "success": true,
  "message": "OK",
  "data": {
    "build_result": {
      "encodes": [
        {
          "preferred_mime_type": "image/jpeg",
          "preferred_extension": "jpg",
          "io_id": 1,
          "w": 585,
          "h": 382,
          "bytes": {
            "physical_file": "test.if.jpg"
          }
        }
      ],
      "performance": {
        "frames": [
          {
            "nodes": [
              {
                "wall_microseconds": 26453,
                "name": "draw_image_to_canvas"
              },
              {
                "wall_microseconds": 19381,
                "name": "primitive_decoder"
              },
              {
                "wall_microseconds": 3567,
                "name": "primitive_encoder"
              },
              {
                "wall_microseconds": 25,
                "name": "create_canvas"
              }
            ],
            "wall_microseconds": 49863,
            "overhead_microseconds": 437
          }
        ]
      }
    }
  }
}%                   
```
![orig](https://user-images.githubusercontent.com/105303/48737663-f2358c80-ec4e-11e8-8412-26dbe96543a8.jpg)
![test if 100](https://user-images.githubusercontent.com/105303/48737664-f2358c80-ec4e-11e8-991f-15e62c7c2d95.jpg)
![test if](https://user-images.githubusercontent.com/105303/48737665-f2358c80-ec4e-11e8-8545-b8ca499a9550.jpg)
![test im](https://user-images.githubusercontent.com/105303/48737666-f2ce2300-ec4e-11e8-9f38-a3c864a107b9.jpg)

**Comment by kepi** [comment]
After some experiments I found out that I'm able to improve results greatly with *build* instead of *ir4* using *hints* and *sharpen_percent* (tried some values from laundry list example).

From there I tried to browse source code and found out that `f.sharpen` argument in *ir4* is working too and it is enough for my current situation (before I tried a.sharpen and s.sharpen - I still don't know what `a`, `s` and `f` stands for... sorry :) ).

Still, IMHO default output of resize operation should provide better result so I'm not closing the issue.

**Comment by kepi** [comment]
One more update. Hardcoded `f.sharpen` doesn't work for us at the end because of same size images. We are using imageflow server to online resize (and optionally crop) images and sharpen works for some of them. Problem is when source image is same size as result image, sharpen then make image even more uggly then before.

Let me know if I can provide more information or help with testing.

**Comment by lilith** [comment]
I've added the `f.sharpen_when=downscaling|sizediffers|always` command to let you control when sharpening happens. This should let you tune the sharpness of text/vector resizing to your liking. The default behavior is tuned for photographs, not vectors. 

Also note that high-dpi screens can confuse results, as images will be upscaled by the browser making them look less sharp. CSS downscaling can restore the sharpness, which is why the above images will look so different from one another on a high-dpi screen.
