### ISSUE TITLE
Cropping of pyramid TIFF

### ISSUE THREAD

**Issue by jramapuram** [imazen/imageflow#206]
Any plans on supporting pyramid tiff? It provides a quick mechanism to crop ultra-large resolution images; currently get this error:

![screenshot from 2018-12-13 14-50-36](https://user-images.githubusercontent.com/8204807/49942776-94f7c880-fee6-11e8-91dd-e66dd8261ee2.png)

**Comment by lilith** [comment]
TIFF support is not currently a priority - all OSS decoders have a poor security record.
