### ISSUE TITLE
imageflow_core and imageflow_c_components depend on different versions of lcms2

### ISSUE THREAD

**Issue by matt4682** [imazen/imageflow#210]
`imageflow_core` depends on the `lcms2` crate which pulls in `lcms2-sys` version `3.1.0` whereas `imageflow_c_components` depends directly on the `lcms2-sys` and selects version`2.4.8`. 

This causes the following build error for me:
```
error: multiple packages link to native library `lcms2`, but a native library can be linked only once

package `lcms2-sys v2.4.8`
    ... which is depended on by `imageflow_c_components v0.1.0 (https://github.com/imazen/imageflow?tag=v1.1.0-rc18#d3226574)`
    ... which is depended on by `imageflow_core v0.1.0 (https://github.com/imazen/imageflow?tag=v1.1.0-rc18#d3226574)`

package `lcms2-sys v3.1.0`
    ... which is depended on by `lcms2 v5.1.3`
    ... which is depended on by `imageflow_core v0.1.0 (https://github.com/imazen/imageflow?tag=v1.1.0-rc18#d3226574)`
```

It looks like the issue was caused by [this commit to lcms2](https://github.com/kornelski/rust-lcms2/commit/c81a780ac2b5772d255453f33d67a0a971354fa7) which bumped up `lcms2-sys` to an incompatible major version.

**Comment by kornelski** [comment]
Fixed in 272312dc936c35b084b7c5debf84b49622800d13
