### ISSUE TITLE
imageflow_core crate not available on crates.io?

### ISSUE THREAD

**Issue by bunnymatic** [imazen/imageflow#233]
Hi

I'm new to rust but old to image processing.  I've been an ImageMagick user for decades.
I'm curious to try out the `imageflow_core` crate directly in my rust code but I don't see it on `crates.io`.  Is that expected?  

If so, can you tell me how to include that crate in my local development?

Thanks, in advance.

Here's my attempt at adding `imageflow_core` and `imageflow` to my `Cargo.toml`
```
$ cargo build
warning: dependency (imageflow_core) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
    Updating crates.io index
error: no matching package named `imageflow_core` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `c5_image_finder_cropper v0.1.0 (/path/to/project)`

$ cargo build
warning: dependency (imageflow) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
    Updating crates.io index
error: no matching package named `imageflow` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `c5_image_finder_cropper v0.1.0 (/path/to/project)`
```

**Comment by bunnymatic** [comment]
I just learned that I can add a git repo to my `Cargo.toml`.  

```
imageflow_core = { git = "https://github.com/imazen/imageflow" }
```

Problem solved.

Do you have plans on releasing this at some point to `crates.io`?

**Comment by lilith** [comment]
I'm planning to wait for a crates.io release until 1.0; currently there aren't enough Rust developers using it to justify tracking API changes.
