### ISSUE TITLE
libimageflow and numpy.ndarray

### ISSUE THREAD

**Issue by BooBSD** [imazen/imageflow#248]
Hello,

I am trying to use `numpy.ndarray` as input image and output result for `libimageflow`, but I can not find any useful information about it. Is it possible at all? Are there any hacks?
Please, give me some advice.

Thank you.

**Comment by lilith** [comment]
`flow_bitmap_bgra_ptr` is one of the nodes in the JSON API, which is usable from libimageflow. You can pass a pointer to a BitmapBgra instance. Are you using Rust?

**Comment by BooBSD** [comment]
@lilith No, I use Python.

**Comment by lilith** [comment]
If you can mimic this C-compatible structure you can pass it into Imageflow: 

https://github.com/imazen/imageflow/blob/f2291e4d7bd433989f84e624af8ab6f46ccb96d5/imageflow_core/src/ffi.rs#L206-L219
