### ISSUE TITLE
Publish basic benchmarks

### ISSUE THREAD

**Issue by e271828-** [imazen/imageflow#292]
The website has some numbers ("10x better" than ImageMagick, "8-200ms" processing time) but no references for them.

It would be nice to see a few numbers in a real benchmark before spending the time to write customized ones for your scenario. Even just average compression RTT on 50KB JPGs, and a breakdown of where the ms are consumed.

**Comment by lilith** [comment]
Benchmark scripts can be found in https://github.com/imazen/imageflow/tree/master/imageflow_tool

imageflow_tool returns a JSON object with the ms breakdown.

**Comment by e271828-** [comment]
@lilith I'm aware of that: publishing some results in a table in the README would be worthwhile, and probably encourage people to spend more time trying out what you've built.
