### ISSUE TITLE
Update docker image for imageflow_server_unsecured

### ISSUE THREAD

**Issue by danieljuhl** [imazen/imageflow#369]
The image hasn't been built/updated since august 2018. Is this intentionally?

https://hub.docker.com/r/imazen/imageflow_server_unsecured

**Comment by lilith** [comment]
No, it's due to a bug in Docker Cloud that I haven't been able to fix. Until I find and configure and alternative docker builder we won't have updates.

**Comment by lilith** [comment]
CI is now pushing docker images again.
