### ISSUE TITLE
Implement watermark examples

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#398]
Implement watermarking examples and figure out how to support them with the Querystring API

**Comment by dcrck** [comment]
I'm interested in a watermark example as well. I use ImageMagick for this currently, and I'd love to figure out how to use the JSON job syntax to put my watermark into my images, so I could use imageflow_tool for the whole pipeline.

**Comment by lilith** [comment]
Would you be willing to share your current imagemagick script so I can ensure your use case is supported?

**Comment by dcrck** [comment]
@lilith Certainly: https://gist.github.com/dcrck/955cd887ca86264c293086da83be717d

**Comment by lilith** [comment]
We now have watermark docs: https://docs.imageflow.io/json/watermark.html

**Comment by lilith** [comment]
* This should align the watermark to the bottom-right of the image.
* It will scale the watermark down if it is larger than the image.
* You can delete or adjust min_canvas_width/height to determine when you'd like to hide the watermark instead of displaying it. 
* You can delete sharpen_percent if you don't want sharpening applied. Usually watermarks need a little sharpening. 

```json
{
  "watermark": {
    "io_id": 1,
    "gravity": { 
      "percentage" : {
        "x": 100,
        "y": 100 
      }
    },
    "min_canvas_width": 50,
    "min_canvas_height": 50,
    "hints": {
      "sharpen_percent": 15
    }
  }
}
```

**Comment by dcrck** [comment]
I've gotten it working on the latest version. Thank you, team, for implementing this!

**Comment by lilith** [comment]
You're welcome! Thanks for using Imageflow.
