### ISSUE TITLE
HEIC/PDF support?

### ISSUE THREAD

**Issue by chessai** [imazen/imageflow#401]
Does imageflow support converting from HEIC _and_ from/to PDF? I just came across imageflow, and it seems really promising. I've been out all day and unable to try it out at a computer. If imageflow is able to do this, it would help a lot with getting it used at my place of work, where we currently use imagemagick in anger.

**Comment by lilith** [comment]
Not currently. We target formats that web browsers support, which does not include heic 

https://caniuse.com/#feat=heif

**Comment by lilith** [comment]
PDF input might happen eventually but PDF output seems an odd choice for the web. Could you share more about that use case?

**Comment by chessai** [comment]
I work at a bank for startups. For some payments, users must provide a purpose for the payment. These can be made up of uploaded documents (not necessarily in PDF), which must be submitted to a partner bank as a PDF.

**Comment by lilith** [comment]
Thanks for sharing this. I'll keep this in mind for when we have a sufficiently secure PDF parser available.

**Comment by sanderkooger** [comment]
@lilith  PDF input would be very helpful for our use case too. The next step in the This Is Fashion platform will be supporting Books, magazines and lookbooks. Im still looking for a good way to make this part work. Video is almost done though. ( Ill trade you a beta test account if you want :P )
