### ISSUE TITLE
Is there a way to do image subtraction with imageflow?

### ISSUE THREAD

**Issue by liufuyang** [imazen/imageflow#409]
For example as I heard in astronomy photography they take a long exposure image and subtract some "dark frame" to remove noise from the picture. Is there a related command in imageflow to do that? Thank you.

**Comment by lilith** [comment]
No we don't currently support this. Is astronomy photography your use case?

**Comment by liufuyang** [comment]
Thank you. I am a totally new amature in astronomy business. Just started recently and I know a little bit of Rust. Saw some people mentioning using free or professional software to do this kind of operaiton called `Dark-frame_subtraction` https://en.wikipedia.org/wiki/Dark-frame_subtraction. Thought it would be cool if our rust software can support it.  I also wonder, would it be difficult to implement or migrate some code into our library? And would this function or feature only supposed to work with `RAW` format? (How about with `JPG` or `PNG`) 

I am just asking something I would like to know more, you don't have to feel pressured to answer everything here :)

**Comment by lilith** [comment]
I think this might be too obscure for us to implement. We also don't support raw files. There does seem to be existing software that does this: https://www.wikiwand.com/en/Dark-frame_subtraction

Perhaps you could shell out to dcraw for your use case?

**Comment by liufuyang** [comment]
Well I was thinking about perhaps help implementing some similar function in Rust here, as I have more experience with Rust than astronomy photography. But I guess I need to get more info on how dcraw does it. It is in C and not sure whether it is still maintained or not. Also I would pretty much like to do this in JPEG format, rather than in RAW, if possible. As  I feel I am a bit more familiar with that JPEG is than RAW, also all my picture is in JPEG format.

**Comment by liufuyang** [comment]
Otherwise I can basically try out some implementation with https://crates.io/crates/image, and ping you back when I have some ideas. For now I know too little on this topic. Thanks for the reply though.
