### ISSUE TITLE
ImageMalformed: CError 60: Image decoding failed : Mozjpeg decoding error: Unsupported color conversion request

### ISSUE THREAD

**Issue by kurtcodemander** [imazen/imageflow#429]
I'm using imageflow_server, but I'm getting an error on many JPG images. 

Versions tried: 1.4.0-rc40 and 1.3.0-rc30. 

The error message: 

> ImageMalformed: CError 60: Image decoding failed : Mozjpeg decoding error: Unsupported color conversion request

Example original JPG: 
[225442_350_Tactic_Green_Blue.jpg](https://kfritid.blob.core.windows.net/upload/2020/03/27/225442_350_Tactic_Green_Blue.jpg)

Link to ImageFlow server for this JPG: 

[225442_350_Tactic_Green_Blue.jpg?maxwidth=500](https://images.larsmonsen.no:39876/images/upload/2020/03/27/225442_350_Tactic_Green_Blue.jpg?maxwidth=500)

Full error details: 

> Internal Server Error
> Info:"https://kfritid.blob.core.windows.net/upload/2020/03/27/225442_350_Tactic_Green_Blue.jpg"
> Error:BuildFailure(Error { httpish_code: 400, message: "ImageMalformed: CError 60: Image decoding failed : Mozjpeg decoding error: Unsupported color conversion request\ncodecs_jpeg.c:38: in function jpeg_error_exit\ncodecs_jpeg.c:881: in function flow_codecs_jpeg_read_frame\ncodecs.c:197: in function flow_codec_execute_read_frame\n at\nimageflow_core\\src\\codecs\\mod.rs:296:17\nhttps://github.com/imazen/imageflow/blob/eaf5dbb1286b17e8ed37bfa131aa64e01152be2e/imageflow_core\\src\\codecs\\mod.rs#L296\nimageflow_core\\src\\flow\\nodes\\codecs_and_pointer.rs:204:65\nhttps://github.com/imazen/imageflow/blob/eaf5dbb1286b17e8ed37bfa131aa64e01152be2e/imageflow_core\\src\\flow\\nodes\\codecs_and_pointer.rs#L204\nimageflow_core\\src\\flow\\execution_engine.rs:459:114\nhttps://github.com/imazen/imageflow/blob/eaf5dbb1286b17e8ed37bfa131aa64e01152be2e/imageflow_core\\src\\flow\\execution_engine.rs#L459\nimageflow_core\\src\\context.rs:248:59\nhttps://github.com/imazen/imageflow/blob/eaf5dbb1286b17e8ed37bfa131aa64e01152be2e/imageflow_core\\src\\context.rs#L248\nimageflow_core\\src\\clients\\stateless.rs:134:72\nhttps://github.com/imazen/imageflow/blob/eaf5dbb1286b17e8ed37bfa131aa64e01152be2e/imageflow_core\\src\\clients\\stateless.rs#L134\nimageflow_core\\src\\clients\\stateless.rs:162:92\nhttps://github.com/imazen/imageflow/blob/eaf5dbb1286b17e8ed37bfa131aa64e01152be2e/imageflow_core\\src\\clients\\stateless.rs#L162\nActive node:\nNodeDebugInfo {\n    stable_id: 2,\n    params: Json(\n        Decode {\n            io_id: 0,\n            commands: None,\n        },\n    ),\n    index: NodeIndex(1),\n}\n" })
> 

For info, with 1.4.0-rc40 it says "libpng warning: iCCP: known incorrect sRGB profile" twice when starting the program. 

Is there a quickfix for this error? I would really like to be able to continue using imageflow_server.

**Comment by lilith** [comment]
That's a CMYK jpeg, which is an Adobe-only format. We will try to add support for them in the future, but for now the best solution is to save them in RGB form before using them with Imageflow.

**Comment by kurtcodemander** [comment]
I see. Thanks for the quick reply.

**Comment by lilith** [comment]
CMYK jpegs are now supported.

**Comment by kurtcodemander** [comment]
Thanks! That's fantastic! I've already updated and it works great. 

> CMYK jpegs are now supported.
