### ISSUE TITLE
Add quantization to WebP Lossless

### ISSUE THREAD

**Issue by domingues** [imazen/imageflow#442]
Is possible to allow quantization on the WebP lossless encoder?

**Comment by lilith** [comment]
Wouldn't WebP Lossy be a better choice? It does a form of quantization during compression.

**Comment by domingues** [comment]
The idea is to have an equivalent file to the produced with pngquant but with the better compression of webp. I'm compressing random screenshots of tutorials, I want to preserve text, but the color detail is a bit irrelevant.

**Comment by lilith** [comment]
Have you tried running it through imageflow twice? You could encode as
lossypng then as webplossless and get the same result.

**Comment by lilith** [comment]
Something like this should work:

```bash
imageflow_tool ir4/querystring --in a.png --out temp.png --command "format=png&png.quality=100&png.min_quality=0&png.lossless=false"
imageflow_tool ir4/querystring --in temp.png --out a.webp --command "format=webp&webp.lossless=true"
```

**Comment by domingues** [comment]
Yes I have done that, but still thinks that will be nice to have that kind of transformation for webp, or even as a generic transformation node. Useful when creating dynamic graphs using fluent apis.

**Comment by lilith** [comment]
I will consider it if there is evidence that it produces much smaller files than can be achieved by another method. What kind of results have you had compared to lossy png or lossy webp?

**Comment by lilith** [comment]
Did lossy PNG + lossless WebP yield significant savings?

**Comment by lilith** [comment]
Please re-open if you can share some data on this.
