### ISSUE TITLE
Add coloring filter

### ISSUE THREAD

**Issue by KartoffelToby** [imazen/imageflow#449]
Add a filter for "pop-coloring" like a accent color

**Comment by lilith** [comment]
Do you have an example of what this would look like?

**Comment by KartoffelToby** [comment]
i mean a change of a specific color in an image, like: https://i.ytimg.com/vi/n9fwiNyDHLI/maxresdefault.jpg

**Comment by lilith** [comment]
I'm kind of confused how it doesn't pick up the lipstick in that example.
Is there a desktop app that does this.

**Comment by KartoffelToby** [comment]
@lilith I'm sorry for the confusion, yes my example has a mistake, all color ranges would change.
Here is a online tool that does this right: https://www.imgonline.com.ua/eng/replace-color.php

**Comment by lilith** [comment]
I think this is out of scope for the simple tasks Imageflow needs to focus on. We may revisit this in the future.
