### ISSUE TITLE
imageflow_server memory consumption

### ISSUE THREAD

**Issue by iuriikomarov** [imazen/imageflow#461]
Hi,

I've just deployed `imageflow_server` to 16GB 6vCPU (hyper-threaded) Ubuntu machine and directed some production traffic to it. This is how memory consumption graph looks like. I do restart the service each 24 hours.

<img width="462" alt="Screenshot 2020-06-22 at 11 00 19" src="https://user-images.githubusercontent.com/295919/85263351-b7718700-b477-11ea-83c9-6cac71a2da95.png">

This deployment serves up to 1K thumbnails per minute, all are downscaled sharped cropped JPEGs and PNGs. `source_cache` size is about 2GB now.

I didn't find any server usage documentations so the questions is: how to calculate normal memory consumption for a given deployment? Does it depend on RPM? Sources size?

```
# imageflow_server -V
imageflow_server release 1.4.0-rc40 (64996dacd* 2020-05-11) for x86_64-unknown-linux-gnu
```

**Comment by lilith** [comment]
Per request, an approximation would be (source pixels * 20+ result pixels * 4). 

It's disturbing that the graph keeps growing. Is that the total memory usage of the server or the memory use of the process?

**Comment by iuriikomarov** [comment]
Total memory usage, but I am pretty sure it's imageflow_server process. I've applied 12-hours restart rule only to it and this is how memory gets cleaned on restarts: 

<img width="462" alt="Screenshot 2020-06-23 at 14 46 49" src="https://user-images.githubusercontent.com/295919/85400122-9769c280-b560-11ea-8cb3-774415af3f25.png">

**Comment by iuriikomarov** [comment]
@lilith May I help somehow to debug the installation and find a problem?

**Comment by lilith** [comment]
Could I get a sample of the image URLs requested and the source images? I will try to recreate this on my end with traffic replay. We would need to run the server under valgrind to find the leak and you probably don't want that speed cut in production.

**Comment by lilith** [comment]
I believe this is solved in 1.4.10. If not, please re-open and we can continue troubleshooting.

**Comment by iuriikomarov** [comment]
Thanks.

Anyway, I've put imageflow_server behind the caching reverse proxy and it stopped to leak.

**Comment by aasiutin** [comment]
Hey @iuriikomarov , behind which reverse proxy did you put imageflow server?

I have the same issue with imageflow_server deployed in Kubernetes. I'm using this image `imazen/imageflow_server_unsecured`.
@lilith  could you please advice which image and tag should I use where memory leak seems to be fixed? 

Thanks,
Oleksii

**Comment by lilith** [comment]
The potential memory leak was fixed in v1.4.10-rc50

 https://github.com/imazen/imageflow/releases/tag/v1.4.10-rc50

https://hub.docker.com/layers/imazen/imageflow_server_unsecured/v1.4.10-rc50/images/sha256-b14f08be4efe2fc725713256bc6f106127c40f809c7c6fd64200cb7b97ed5f25?context=explore

**Comment by aasiutin** [comment]
Thank you, @lilith !

**Comment by khanh0123** [comment]
Hi. I'm using the latest version and am having the same problem. My memory doesn't clean up automatically until I restart it. Version i use is v1.7.0-rc64.

**Comment by lilith** [comment]
We are discontinuing imageflow_server in favor of Imageflow.Server, which
is production ready and vastly more capable.

Imageflow_server was designed around a web framework that is now long
deprecated. I suspect that is the root of the issue, since Imageflow itself
(that processes images) isn't demonstrating this problem).
