### ISSUE TITLE
Mounting S3 storage - tokens are ignored

### ISSUE THREAD

**Issue by Svarto** [imazen/imageflow#495]
Hi, I am playing around with imageflow to see if this can serve my needs. I have a S3 bucket where each file is accessible by an url + token combination. I run into the problem that as the token is in the URL, it is essentially stripped out as imageflow takes it and assumes it will be a command to itself (i.e. it is not passed along to my S3 storage).

For example, the file is accessible on:
`https://minio.imagestore.com/storage/user/filename.jpg?token=<10 characters>`

So when I try and access it through:
`https://imageflow.imagestore.com/minioprefix/user/filename.jpg?token=<10 characters>?w=300`

Then I get the error that the file is not accessible at (notice, the token has been stripped out on the request from imageflow to the S3 storage):
`https://minio.imagestore.com/storage/user/filename.jpg`

Not sure if there is any way to work around this?

For completeness, I am running the imazen/imageflow_server_unsecured docker with the start command:
`imageflow_server start --bind-address 0.0.0.0 --mount /minioprefix/:ir4_http:https:://minio.imagestore.com/storage/ --data-dir /imageflow_data`

**Comment by lilith** [comment]
Have you considered using imageflow-dotnet-server? It supports s3 directly.

Https://github.com/imazen/imageflow-dotnet-server

Imageflow_server is sadly not nearly as full featured yet.

**Comment by Svarto** [comment]
@lilith thanks for the quick reply! I will have a look, I have no experience with ASP.net so not 100% I can manage the install instructions. Will make an attempt but might need to get back to you for some help. Will close this issue for now.
