### ISSUE TITLE
Binaries for ubuntu 20.04 

### ISSUE THREAD

**Issue by israellot** [imazen/imageflow#505]
I was wondering when binaries for ubuntu 20.04 will become available, since it is a new LTS release.

**Comment by lilith** [comment]
Binaries for 18.04 will work fine on 20.04.

**Comment by lilith** [comment]
Are you using nuget?

**Comment by israellot** [comment]
Thanks for your response @lilith 
Yes, I’m using nugget and dotnet core. As you may have guessed, the binaries are not found on Ubuntu 20.04, I’ve looked up the code and the search paths take into account the platform.

**Comment by lilith** [comment]
The Ubuntu 16.04 nuget package now targets linux-x64 and should work across all linux platforms that have GLIBC 2.23 or higher.
