### ISSUE TITLE
Hard Coded Containers in Azure

### ISSUE THREAD

**Issue by hn1** [imazen/imageflow#511]
When using ImageFlow, it seems one has to hard code the Azure Containers in Startup of an MVC Core application.
As we are creating containers dynamically, is there any way one can avoid this?
Thanks

**Comment by lilith** [comment]
Could you open this on the imageflow-dotnet-server repo instead? You may
want to use your own blob provider - they're quite easy to make.

**Comment by lilith** [comment]
https://github.com/imazen/imageflow-dotnet-server/issues/23
