### ISSUE TITLE
Getting "Error 9: Wrong input color space on transform" transforming jpeg

### ISSUE THREAD

**Issue by aheintz** [imazen/imageflow#512]
Transforming the image below returns an error (using the dotnet library), and I cannot really figure out why:

```
Imageflow.Bindings.ImageflowException: ImageMalformed: Error 9: Wrong input color space on transform (ObjectCreationError) at
imageflow_core/src/codecs/color_transform_cache.rs:126:197
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/codecs/color_transform_cache.rs#L126
imageflow_core/src/codecs/color_transform_cache.rs:196:152
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/codecs/color_transform_cache.rs#L196
imageflow_core/src/codecs/mozjpeg_decoder.rs:342:35
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/codecs/mozjpeg_decoder.rs#L342
imageflow_core/src/flow/nodes/codecs_and_pointer.rs:208:65
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/flow/nodes/codecs_and_pointer.rs#L208
imageflow_core/src/flow/execution_engine.rs:488:114
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/flow/execution_engine.rs#L488
imageflow_core/src/context.rs:284:59
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/context.rs#L284
imageflow_core/src/context_methods.rs:50:68
https://github.com/imazen/imageflow/blob/1a7e1eecd8f04cab4413b48c2bf8bd5bbf140f5d/imageflow_core/src/context_methods.rs#L50
Active node:
NodeDebugInfo {
    stable_id: 1,
    params: Json(
        Decode {
            io_id: 0,
            commands: None,
        },
    ),
    index: NodeIndex(1),
}


   at Imageflow.Bindings.JobContext.AssertReady()
   at Imageflow.Bindings.JobContext.SendJsonBytes(String method, Byte[] utf8Json)
   at Imageflow.Bindings.JobContext.Execute[T](T message)
   at Imageflow.Fluent.ImageJob.FinishAsync(JobExecutionOptions executionOptions, SecurityOptions securityOptions, CancellationToken cancellationToken)
   at Imageflow.Fluent.FinishJobBuilder.InProcessAndDisposeAsync()
   at ImageScalingService.Controllers.ImageScalingController.GetImage(Int32 clientId, String requestedImageGuid, Boolean downloadContent, ResizeInstructions resizeInstructions) in /Users/heintz/Projects/storm/ImageScalingService/ImageScalingService/src/Controllers/ImageScalingController.cs:line 450

```

The image: https://media.cdn.storm.io/62/fa457334-0cd4-4839-ad6d-1808f921f5e6

**Comment by lilith** [comment]
This looks like an sRGB image with a CMYK color profile attached. Clearly that doesn't make sense, so Imageflow throws this error. 

To ignore the error, use `&ignore_icc_errors=true` in the command string.

**Comment by aheintz** [comment]
Thanks for the response. I agree that it doesn't make sense. Unfortunately, `&ignore_icc_errors=true` doesn't make any difference (I'm using the .net dotnet library if that makes any difference, and are indeed using the `ResizerCommands` method).

I resolved my problem by using ImageMagick to correct the color profile if ImageFlow fails. It doesn't seem to be a terribly uncommon problem, I'm having quite a few images with this "error".

**Comment by lilith** [comment]
I tested ignore_icc_errors with that image and it worked. Could you share
the full C# code you are using?

**Comment by lilith** [comment]
Use b.BuildCommandString instead. You're decoding the image before applying
the ignore_icc_errors command.

**Comment by aheintz** [comment]
Oh, that worked like a charm! Thanks for your help, saved my night! 😄

**Comment by patrickmichalina** [comment]
@lilith how can we apply this to the node package?

**Comment by lilith** [comment]
What code are you currently using?

**Comment by patrickmichalina** [comment]
This sort of flow is how we are doing it:

```ts
    const streams = this.prepareStreamsForProcess(asset, hash)

    const inStream = new FromStream(streams.input)
    const outStream = new FromStream(streams.output)

    return new Steps(inStream)
      .constrainWithin(query.width, query.height)
      .encode(outStream, this.getFormat(query.format, query.quality))
      .execute()

```

All of a sudden getting a bunch of these errors "Wrong input color space on transform" and wondering how to possibly mute this like noted in the thread here.

**Comment by patrickmichalina** [comment]
`/home/runner/.cargo/git/checkouts/imageflow-ce6f29762d899395/1a7e1ee/imageflow_core/src/codecs/color_transform_cache.rs:126:197`

**Comment by anshulrgoyal** [comment]
@patrickmichalina I will check if we support these options in the nodejs package, if not I will add it.

**Comment by patrickmichalina** [comment]
@anshulrgoyal much appreciated!

**Comment by anshulrgoyal** [comment]
@patrickmichalina We have added a new DecodeOptions type to the imageflow node which passed as the second argument to the `decode` method and Step class constructor. I will release the update package within a few minutes and it will be available in a few hours.

**Comment by anshulrgoyal** [comment]
@patrickmichalina The package is live and I have added an example in read me.

**Comment by patrickmichalina** [comment]
Fantastic thank you very much appreciated for the quick update. This will fix our production tool
