### ISSUE TITLE
Watermark support for server

### ISSUE THREAD

**Issue by NorthFoxz** [imazen/imageflow#513]
Hi, I love your project!
I'm a rust dev and currently working on an actix-web server. There's no document for imageflow-core so I'm currently running the imageflow independently.
I'm wondering if you guys will support watermark funtionality for imageflow-server in the future?

**Comment by lilith** [comment]
Yes I plan to support watermarks in the future, specifically when I rewrite
imageflow_server in a modern framework. In the meantime I suggest using
Imageflow .NET Server, as that one is far more polished.

**Comment by lilith** [comment]
imageflow_server is obsolete: https://github.com/imazen/imageflow/issues/598

Imageflow.NET Server supports watermarks.
