### ISSUE TITLE
Problem converting from PNG to JPEG (without scaling)

### ISSUE THREAD

**Issue by aheintz** [imazen/imageflow#538]
I'm having an issue with converting PNG image to JPEG (when not scaling), the transparent PNG background gets a weird effect. IF the image is scaled, in any direction, it's not a problem.

Original image: https://s3.eu-north-1.amazonaws.com/media.storm.io/original_png_image.png
Converted image: https://s3.eu-north-1.amazonaws.com/media.storm.io/png_to_jpeg_image.png

I'm using the following:
- Imageflow.Net version 0.7.6
- Imageflow.NativeRuntime.osx_10_11-x86-64 1.4.11-rc51

Code used to convert image:
````c#
await new ImageJob().BuildCommandString(
                        new StreamSource(input, true),
                        new StreamDestination(output, false),
                        "format=jpeg")
                    .Finish()
                    .InProcessAndDisposeAsync();
````

**Comment by lilith** [comment]
Does this still occur if you set &bgcolor=white in the command string?

**Comment by aheintz** [comment]
Yes,  it still occurs using bgcolor=white, I'm currently using `f.sharpen=1` as a workaround.

**Comment by lilith** [comment]
This is fixed in `main` and will be rolled into the next release. Thank you so much for helping us find this!
