### ISSUE TITLE
Support for using imageflow_server with private aws buckets

### ISSUE THREAD

**Issue by vino-jasuba** [imazen/imageflow#543]
Does imageflow support retrieval of images from private S3 buckets using either an authorization string or a pre-signed URL?

**Comment by lilith** [comment]
Not yet, but Imageflow .NET Server does and it runs on docker.

**Comment by vino-jasuba** [comment]
I guess I'll give that a try. The setup instructions are the same as in the [Readme](https://github.com/imazen/imageflow/blob/main/README.md)?

**Comment by lilith** [comment]
No, you'll want to look in the readme and examples folder of
https://github.com/imazen/imageflow-dotnet-server

There are two examples with Docker, so just copy/paste and edit.

**Comment by lilith** [comment]
imageflow_server is obsolete: https://github.com/imazen/imageflow/issues/598
