### ISSUE TITLE
Notes for animated GIF support

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#55]
- One must loop through all frames and expand the 'screen size' to (left + width), (top + height) for each frame. Negative left/top coordinate handling unexplored.
- Perhaps we should quantize in linear light?
- Global color map optimization seems challenging

**Comment by stravid** [comment]
Do you have thoughts on extracting frames from animated GIFs? The use case I'm thinking of involves scenarios where you display small image previews and don't want animated GIFs. In such a case I usually extract a single frame and use this as preview for animated GIFs.

**Comment by nathanaeljones** [comment]
Frame extraction will be supported.

**Comment by nathanaeljones** [comment]
Closing as duplicate of #116
