### ISSUE TITLE
How to use permacache_proxy

### ISSUE THREAD

**Issue by max-frai** [imazen/imageflow#550]
Hello, I want to serve images from static folder with results caching.
I try the following run command (on macos):
```
cargo run --bin imageflow_server start --port 4243  --data-dir=./imageflow_data --mount /js/:permacache_proxy:./js
```
So I have `js` and `imageflow_data` folders. `js` folder has `test.jpg` file.

I try to access it: `http://localhost:4243/js/test.jpg?width=300` which leads to error:

```
Internal Server Error
Info:"./jstest.jpgwidth=300"
Error:UpstreamReqwestError(Error(Url(RelativeUrlWithoutBase)))
```

What's wrong?

**Comment by lilith** [comment]
permacache_proxy proxies http content from another server. It doesn't serve
static files.

**Comment by lilith** [comment]
You can use the `static` handler for images, but imageflow_server is not a general purpose HTTP server. 

I would suggest using [Imageflow.NET Server](https://github.com/imazen/imageflow-dotnet-server) as it can serve arbitrary file types alongside image resizing.

**Comment by lilith** [comment]
Feel free to reopen if you have any follow up questions
