### ISSUE TITLE
Cropping an EXIF Orientated Image

### ISSUE THREAD

**Issue by homesar** [imazen/imageflow#553]
The cropped area for an image with EXIF orientation set is being incorrectly displayed.  Using these source images:
https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/orientation/portrait_1.jpg
https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/orientation/portrait_6.jpg

I've cropped the image to show just the waterfall.  The image with no orientation appears correctly, while the crop area on the left oriented image is off.

portrait_1.jpg?crop=134,155,279,439
![image](https://user-images.githubusercontent.com/14047923/97099686-1df2f580-1662-11eb-8df5-4410dbe52822.png)

portrait_6.jpg?crop=134,155,279,439
![image](https://user-images.githubusercontent.com/14047923/97099689-2a774e00-1662-11eb-8676-a0d5fff2a808.png)

Alternatively, if it's possible to disable the automatic rotation, I'd be fine with rotating the source image and cropping at the same time.

**Comment by lilith** [comment]
This is fixed in v1.4.13-rc53.
