### ISSUE TITLE
[QUESTION] Why is rustc_serialize being used?

### ISSUE THREAD

**Issue by aspenluxxxy** [imazen/imageflow#569]
I was attempting to compile this, and ran into errors relating to `rustc_serialize`

Upon further investigation, I found that `rustc_serialize` has been considered deprecated for years ([since April 2017, to be exact](https://github.com/rust-lang-deprecated/rustc-serialize/commit/660c18a02f8a7aca84380353be8a34e5a49568c4)), and I'm curious, why is this still being used?

**Comment by lilith** [comment]
Thank you for reporting this. 

It was used for base64 and hexadecimal encoding. I've just pushed an update to main that replaces it with the base64 and hex crates. Imageflow was started in 2014, so we do use a few older crates.

**Comment by lilith** [comment]
Also, apologies for the unpolished Rust interface. This library is primarily used by non-rust (C#, Node, Elixir, Golang, etc) clients, so my focus has gone into those bindings and corresponding servers. If you can share more about your usage scenario I can probably help give you a cleaner API.
