### ISSUE TITLE
Png -> jpg conversion became >10x slower at v1.5.3-rc57

### ISSUE THREAD

**Issue by ogliznutsa** [imazen/imageflow#576]
Starting from `v1.5.3-rc57` png->jpg conversion is >10x slower.

[Tests.zip](https://github.com/imazen/imageflow/files/5952285/Tests.zip)

Imageflow.Net `v0.7.21` + Imageflow.NativeRuntime.win-x86_64 `v1.5.2-rc56`:
```
Using ImageResizer to convert input.png -> imageresizer*.jpg in qualities 90..90 using maxwidth=500&format=jpg with parallel=True
Completed in 00:00:01.0542554
Using Imageflow to convert input.png -> imageflow_jpeg_turbo*.jpg in qualities 90..90 using maxwidth=500&format=jpg&jpeg.turbo=true with parallel=True
Completed in 00:00:00.3769430
Using Imageflow to convert input.png -> imageflow*.jpg in qualities 90..90 using maxwidth=500&format=jpg with parallel=True
Completed in 00:00:00.0383334
```

Imageflow.Net `v0.7.21` + Imageflow.NativeRuntime.win-x86_64 `v1.5.3-rc57`:

```
Using ImageResizer to convert input.png -> imageresizer*.jpg in qualities 90..90 using maxwidth=500&format=jpg with parallel=True
Completed in 00:00:01.0349054
Using Imageflow to convert input.png -> imageflow_jpeg_turbo*.jpg in qualities 90..90 using maxwidth=500&format=jpg&jpeg.turbo=true with parallel=True
Completed in 00:00:04.2465038
Using Imageflow to convert input.png -> imageflow*.jpg in qualities 90..90 using maxwidth=500&format=jpg with parallel=True
Completed in 00:00:03.9138465
```

imageflow-dotnet-server gets stuck when doing such conversion - when deployed to Azure App Service (B1 app plan), it takes more than 40 seconds to convert 3 png files to jpg. We temporary downgraded imageflow-dotnet-server to `v0.5.1` to use old native runtime under the hood.

**Comment by ogliznutsa** [comment]
@lilith could you please comment on the issue? Is it a bug or expected behavior?

**Comment by lilith** [comment]
I added proper background color rendering so that transparent pngs are not
corrupted when converting to jpegs.

This is probably the cause. I assume this is only happening with 32 bit but
not 24 bit PNGs?

**Comment by ogliznutsa** [comment]
Yes, 24 bit PNGs are not affected

**Comment by ogliznutsa** [comment]
@lilith Yes, 24 bit PNGs are not affected

**Comment by lilith** [comment]
This is the offending code: https://github.com/imazen/imageflow/blob/main/imageflow_core/src/graphics/blend.rs#L23-L43

There's no obvious way to fix the performance without sacrificing blending accuracy, so this may take a while to optimize/resolve.

**Comment by lilith** [comment]
Previously, transparent areas of PNGs were simply lifted to opacity with whatever random color data happened to be stored in those pixels, which caused lots of artifacts.

**Comment by bwaldron** [comment]
Thanks @lilith, sounds like the same. Would you recommend setting the background color (bgcolor) to avoid the perf cost for now?

**Comment by lilith** [comment]
It won't help - the default bgcolor is white.

**Comment by lilith** [comment]
I found a way to optimize it drastically. Try v1.5.6-rc60

**Comment by bwaldron** [comment]
Much appreciated, thanks!
________________________________

**Comment by ogliznutsa** [comment]
Now works much faster, thanks @lilith !
