### ISSUE TITLE
No NativeRuntime compatible with net5.0 sdk docker images

### ISSUE THREAD

**Issue by andreasmwestberg** [imazen/imageflow#577]
https://hub.docker.com/_/microsoft-dotnet-sdk

**Comment by lilith** [comment]
I'm confused - we have examples on .net50 sdk docker images

https://github.com/imazen/imageflow-dotnet-server/blob/main/examples/Imageflow.Server.ExampleDocker/Dockerfile

**Comment by andreasmwestberg** [comment]
sorry I think I put this issue in the wrong repository, I'm referring to [imageflow-dotnet](https://github.com/imazen/imageflow-dotnet)

**Comment by lilith** [comment]
Those packages are actually generated by this repository, so it's fine. 

I'm just confused why https://www.nuget.org/packages/Imageflow.NativeRuntime.ubuntu_16_04-x86_64/1.5.5-rc59 doesn't work for you. It should be compatible with all reasonably recent linux distros that include glibc.

**Comment by andreasmwestberg** [comment]
I've tested all net5 images which didn't work for me, but now that you mentioned that I went back to check and I noticed I had forgotten that for the last layer in the docker file I'd switched to an alpine based image to keep the size down, which doesn't use glibc

my fault, user error
