### ISSUE TITLE
WebPLossy colour is desaturated?

### ISSUE THREAD

**Issue by Amethi** [imazen/imageflow#588]
Hello. When using the WebPLossy encoder preset over MozJpeg, the image seems quite desaturated. I've checked this with a few images, but it's most noncable in the example below (jpeg left/webp right):

https://1drv.ms/u/s!AlJ8J3Tnj5ejjdlyBl1w5V00bymeRg?e=5FOQdg

Is this expected? Do I need to adjust a colour profile or something? Thanks.

**Comment by lilith** [comment]
It probably is a color profile issue. I'd inspect the two images to see
what profiles are attached, and then check your monitor profile.

Also looks like you're using two different apps. If you open them both in
Chrome do you still see the issue? Different apps might apply different
default color profiles.

**Comment by Amethi** [comment]
Thanks Lilith. You're spot on with the different-app point. Loading them both in (new) Edge showed them the same, desaturated. Even the original image. I think it's my monitor profile (it's meant to be set to SRGB). Sorry to bother :)
