### ISSUE TITLE
docs.imageflow.io appears to be down with a 404 error

### ISSUE THREAD

**Issue by zhuoyue95** [imazen/imageflow#604]
It appears that [docs.imageflow.io](https://docs.imageflow.io) is down. I got a GitHub 404 page telling me that there isn't a GitHub Pages site here.

**Comment by gebrits** [comment]
All can we please bring these docs back? Should be a real issue fix.

**Comment by rikjacobs1390** [comment]
Docs are still down. Is it possible to fix this
![Screenshot 2022-08-09 at 10 59 52](https://user-images.githubusercontent.com/20502067/183608983-49366382-d55f-47ed-add9-08196cfaebd2.png)
?

**Comment by gebrits** [comment]
Waybackmachine has something here: https://web.archive.org/web/20210525023852/https://docs.imageflow.io/

**Comment by cfcode** [comment]
I found this:
https://imazen.github.io/imageflow/
Looks like the url is changed?

**Comment by lilith** [comment]
Sorry for the delay in fixing this. Github overhauled Pages to use Actions, and something broke invisibly, I had to replace the whole pipeline to fix it :|

docs.imageflow.io is up. I suspect https://docs.imageflow.io/ may be outdated.
