### ISSUE TITLE
bug: docs site gives 404

### ISSUE THREAD

**Issue by ryanrussell** [imazen/imageflow#610]
## Bug
Primary repo link and links in the readme fail

### Details
Tried a couple docs links, both giving a 404:
- https://docs.imageflow.io/
- https://docs.imageflow.io/querystring/introduction.html

### Screenshot
![image](https://user-images.githubusercontent.com/523300/189383539-01252acf-2f87-46b0-b2db-241a3b6f9599.png)

Request 
![image](https://user-images.githubusercontent.com/523300/189384044-b5292d7c-a59e-41ab-b44a-8c8ffcd9401c.png)

Best,
Ryan

**Comment by lilith** [comment]
Sorry for the delay in fixing this. Github overhauled Pages to use Actions, and something broke invisibly, I had to replace the whole pipeline to fix it :|.
