### ISSUE TITLE
Some png files when resized with png.quality results as empty/transparent png file

### ISSUE THREAD

**Issue by tvatavuk** [imazen/imageflow#613]
We need to resize this `demo.png` image.

![image](https://user-images.githubusercontent.com/2724850/202019644-0565fb1b-dde3-4174-8485-b5013fbd43f7.png)

Issue happens with parameters: `demo.png?w=1230&h=760&png.quality=75&mode=crop&scale=both`

![image](https://user-images.githubusercontent.com/2724850/202020010-21736309-dd67-4d8c-a251-ec0dfd0d2c73.png)

If we append `png.lossless=true` than resized image looks OK, 
except that we can not control quality `demo.png?w=1230&h=760&png.quality=75&mode=crop&scale=both&png.lossless=true`

![image](https://user-images.githubusercontent.com/2724850/202020279-81f3764b-555f-4b17-8f8e-8d938c2fe194.png)

Issue happens with code that is using following dependencies:
- Imageflow.Net (0.8.5)
- Imazen.HybridCache (0.7.7)
- Imazen.Common (0.7.7)
- Imageflow.NativeRuntime.win-x86 (1.7.3-rc67)
- Imageflow.NativeRuntime.win-x86_64 (1.7.3-rc67)

Same code works as expected with older version of dependencies:
- Imageflow.Net (0.7.24)
- Imazen.HybridCache (0.5.10)
- Imazen.Common (0.5.10)
- Imageflow.NativeRuntime.win-x86 (1.5.8-rc62)
- Imageflow.NativeRuntime.win-x86_64 (1.5.8-rc62)

Same issue is tracked here: https://github.com/2sic/2sxc/issues/2932

Please check https://github.com/2sic/2sxc/issues/2932#issuecomment-1315639045

**Comment by lilith** [comment]
So, I created an integration test on the latest version - but it works on my machine. Can you verify this is the correct input file? Maybe GitHub reencoded it?
https://imageflow-resources.s3.us-west-2.amazonaws.com/test_inputs/png_turns_empty.png

Using w=1230&h=760&png.quality=75&mode=crop&scale=both, I get https://imageflow-resources.s3.us-west-2.amazonaws.com/visual_test_checksums/0E5E63543D35A149D.png

**Comment by lilith** [comment]
Hmm, this is failing on windows but not linux.

**Comment by lilith** [comment]
And yet even on windows the result *looks* correct, despite being compressed differently. Can the problem image be emailed to lilith@imazen.io to make sure GitHub isn't 'repairing' it? Also, can you try with the very latest Imageflow release? This was listed as being in an older version.

**Comment by lilith** [comment]
So, GitHub apparently re-compresses images. The image you e-mailed me is a 24-bit PNG, 18.4KB, and the image GitHub lets me access is a 32-bit PNG, 27.5KB

**Comment by lilith** [comment]
This was specific to PNG files with a zero alpha channel, encoded when using lossy PNG, and when no transparency-inducing operations are performed. Thank you for e-mailing the problematic file, that allowed me to diagnose the issue.
