### ISSUE TITLE
jpeg Quality: bug or feature

### ISSUE THREAD

**Issue by bes-internal** [imazen/imageflow#624]
imagemagick reference:
```
$ magick convert -quality 90 orig.jpg im.jpg && identify -verbose im.jpg |egrep 'Quality|Filesize'
  Quality: 90
  Filesize: 5.2085MiB
$ magick convert -quality 88 orig.jpg im.jpg && identify -verbose im.jpg |egrep 'Quality|Filesize'
  Quality: 88
  Filesize: 5.1116MiB
$ magick convert -quality 60 orig.jpg im.jpg && identify -verbose im.jpg |egrep 'Quality|Filesize'
  Quality: 60
  Filesize: 2.72034MiB
$ magick convert -quality 30 orig.jpg im.jpg && identify -verbose im.jpg |egrep 'Quality|Filesize'
  Quality: 30
  Filesize: 1.86795MiB
```
imageflow:
```
$ imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=90" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Quality: 76
  Filesize: 4.08833MiB
$ imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=88" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Quality: 70
  Filesize: 4.08833MiB
$ imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=60" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Filesize: 4.08833MiB
$ imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=30" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Filesize: 4.08833MiB
```

version with removed files
```
$ rm imageflow2.jpg && imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=90" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Quality: 76
  Filesize: 4.08833MiB
$ rm imageflow2.jpg && imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=88" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Quality: 70
  Filesize: 3.76498MiB
$ rm imageflow2.jpg && imageflow_tool v1/querystring --in orig.jpg --out imageflow2.jpg --command "format=jpeg&jpeg.quality=60" --quiet && identify -verbose imageflow2.jpg |egrep 'Quality|Filesize'
  Filesize: 2.05989MiB
```

Questions:
1. The file is not overwritten?
2. But where did the quality field disappear from the last processing?
3. Quality: bug or feature? Or an attempt to cheat?..

**Comment by bes-internal** [comment]
I saw the main offer of this tool is "get higher-quality images with smaller file sizes". This raises some doubts even if you have new efficient implementation of algorithms. If you just use open libs implementations, then it's still not clear where the smaller file size is taken from, except at the downgrade of quality.
Anyway but why the quality field (I don’t know how it is displayed or filled) has a value not equal as transferred to the tool. It would be convenient to use these data later.

**Comment by lilith** [comment]
We're not just using mozjpeg, we have adaptive algorithms to tune chroma
and other data. What matters, in my opinion, are the following factors:

1. Perceptual image quality
2. File size and browser decoding speed
3. Processing time
4. Security, specifically resistance to malicious image files. Please take
a look at
https://www.cvedetails.com/vulnerability-list/vendor_id-1749/Imagemagick.html

ImageMagick's reported quality setting is bogus, and as I mentioned this
value is meaningless as it does not translate into similar math or
algorithms across codecs.

**Comment by lilith** [comment]
If you select a set of images (say - 4 to 8), we can process them side-by-side with ImageMagick and Imageflow to compare the balance of visual quality and file size.
