### ISSUE TITLE
Issue with very small images failing on Apple / Safari Desktop

### ISSUE THREAD

**Issue by iJungleboy** [imazen/imageflow#635]
We're using ImageFlow through the .net wrapper in the CMS-Plugin 2sxc to extend the platforms Dnn and Oqtane.

Recently, a user reported that if the images get fairly small, they simply don't show and also look strange in the file manager on Apple when downloaded. 

The user created fairly extensive examples here: https://github.com/2sic/2sxc/issues/3111#issuecomment-1693581320

As you can see, he also included a resized image which in the small size causes problems, and included a print-screen of the very same Github page showing this image - which fails in Safari.

Any ideas?

Thanks, iJungleboy

**Comment by lilith** [comment]
https://github.com/2sic/2sxc/issues/3111#issuecomment-1696109486

Does not reproduce in Imageflow.Server 0.8.1 or 0.7.8, appears to be a third party proxy issue inflating responses to a minimum of 4096 bytes.
