### ISSUE TITLE
How to use imageflow_tool on a managed server

### ISSUE THREAD

**Issue by felixranesberger** [imazen/imageflow#636]
I'd like to generate images using a PHP script on my Linux server.
The PHP script will call `imageflow_tool` using the `exec_shell` function

Before I write any PHP, I wanted to try it on the terminal manually using the following command.

```bash
./imageflow_tool'
```

I get the following error:

```bash
./imageflow_tool: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
```

I'm not really deep into servers, but I guess the library `libmvec` is missing on my server?

Is there some way to just upload the `imageflow_tool` executable on my server and run it, without installing any dependencies?

Thanks for any help in advance :)

**Comment by lilith** [comment]
It sounds like you have an outdated (or far less likely, missing) libc
version. Is updating the OS an option?

**Comment by felixranesberger** [comment]
Hi @lilith , sorry for the late response. 

I found out that the `imageflow_tool` worked in a docker container that we use for a customer for hosting.

I found this article on how to check my `libc` version. 

I used `ldd --version` and both servers output the same response:

`ldd (Debian GLIBC 2.31-13+deb11u6) 2.31`

Does this help?

**Comment by lilith** [comment]
2.31 should work - and it wasn't?
