### ISSUE TITLE
"'cargo' is required, but missing" error on Windows

### ISSUE THREAD

**Issue by IvanSmiths** [imazen/imageflow#651]
Super newbie here.
I've encountered an issue while attempting to build Imageflow locally on Windows 11. 
I Followed all the steps in the "Windows 10 Pre-requisites", no errors so far.
After installing everything, i started from the "Building from Source without Docker" part. 
Each `./build.sh` command runs smoothly, but not the `./build.sh install`, where i get this error "`'cargo' is required, but missing. Try: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta`". I have run `./build.sh release` before it.

As suggested by the docs, I have checked the `ci/wintools/SETUP_PATH.bat` file which contains all the necessary paths, and i am running all the build commands using the file `win_enter_env.bat`.

I have also tried by building using cargo, but when i run this command: `cargo build --package imageflow_tool --release`, i get this error: ```
error: package ID specification `imageflow_tool` did not match any packages

        Did you mean `imageflow_core`?
```

What am i missing? Any help will be highly appreciated, thanks in advance

**Comment by lilith** [comment]
Cargo build is the preferred method - github actions files provide the most updated steps.

Do you run cargo build from the repo root?

**Comment by IvanSmiths** [comment]
Yes, i run it from the root. I saw that i am the only one having this problem, If i have to guess, i still need some packages to be installed properly, i am new to Rust, and i am probably missing something.

Thank you for your message.

**Comment by lilith** [comment]
Try running: cargo build --all --release
