### ISSUE TITLE
C# Bindings/API

### ISSUE THREAD

**Issue by SamuelEnglard** [imazen/imageflow#67]
I wanted to start the conversation on the C# Bindings/API

Primarily at this point that means designing the API surface.

**Comment by nathanaeljones** [comment]
Hi! 

Two things: 
1. All flow_graph_* and flow_node_* API surfaces will be replaced by a single JSON api. This will cut the API surface down drastically.
2. There's a basic ruby wrapper here: https://github.com/imazen/imageflow/tree/master/wrappers/ruby/lib


Here's the subset of the API that would be used by the C# bindings. (in ruby FFI syntax). Check [imageflow.h](https://github.com/imazen/imageflow/blob/master/imageflow.h) for param names.

- attach_function :flow_context_create, [], :pointer
- attach_function :flow_context_destroy, [:pointer], :void
- attach_function :flow_context_error_and_stacktrace, [:pointer, :pointer, :uint, :bool], :int64
- attach_function :flow_context_has_error, [:pointer], :bool
- attach_function :flow_context_error_reason, [:pointer], :int
- attach_function :flow_context_clear_error, [:pointer], :void
- attach_function :flow_io_create_for_file, [:pointer, :flow_io_mode, :string, :pointer], :pointer
- attach_function :flow_io_create_from_memory, [:pointer, :flow_io_mode, :pointer, :uint64, :pointer, :pointer], :pointer
- attach_function :flow_io_create_for_output_buffer, [:pointer, :pointer], :pointer
- attach_function :flow_io_get_output_buffer, [:pointer, :pointer, :pointer, :pointer], :bool
- attach_function :flow_job_add_io, [:pointer, :pointer, :pointer, :int32, :flow_direction], :bool
- attach_function :flow_job_create, [:pointer], :pointer
- attach_function :flow_job_destroy, [:pointer, :pointer], :bool
- attach_function :flow_job_configure_recording, [:pointer, :pointer, :bool, :bool, :bool, :bool, :bool], :bool
- attach_function :flow_job_execute, [:pointer, :pointer, :pointer], :bool, blocking: true
- attach_function :flow_job_get_decoder_info, [:pointer, :pointer, :int32, :pointer], :pointer, blocking: true

Note that that the last two API functions will be refactored to use JSON instead of structures. This refactoring hasn't taken place yet. 

Hopefully this helps provide a sense of the (limited) scope of work required. We have no documentation right now about the JSON schema that will be used, but hope to publish that in the next week or so.

**Comment by nathanaeljones** [comment]
FFI API docs are now online. The interface should be pretty stable, but there is a slight chance that memory ownership semantics will be forced to change as more of the core is ported to rust.

These are uploaded as part of CI, and should be updated daily.

https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/imageflowrs/index.html

**Comment by nathanaeljones** [comment]
Ideally we won't see FFI breakage, but rather spend more time refining the JSON message API, which should be much easier to debug.

**Comment by SamuelEnglard** [comment]
@nathanaeljones trying to view the index gives me a 403

**Comment by nathanaeljones** [comment]
I fixed the link, sorry! Did some reorganization. There are also windows binaries of libimageflowrs.dll available, although the JSON message API only responds to "teapot" at the moment. 

https://ci.appveyor.com/project/imazen/imageflow/build/1.0.303/job/h3afay5mhfoi2jvt/artifacts

**Comment by nathanaeljones** [comment]
Let me know if I can improve the clarity of the API docs. There's not much to document on imageflow_send_json yet, but those schemas should be coming this week.

**Comment by nathanaeljones** [comment]
@SamuelEnglard, will #81 be problematic for the C# API?

**Comment by SamuelEnglard** [comment]
#81 will be an issue in that there's just no way to not transfer the C string memory to the GC's control. The best we could do would be to have C# allocate the error message memory and we fill it.

**Comment by nathanaeljones** [comment]
New docs, small API changes, but much higher confidence level: https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/imageflowrs/index.html

**Comment by nathanaeljones** [comment]
Ruby bindings have been updated and are passing all tests again. Over 60% of bugs were discrepancies between camelCasing and snake_casing.

**Comment by nathanaeljones** [comment]
The JSON API docs now live here: 

https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/context_json_api.txt
https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/job_json_api.txt

There is finally some documentation on packaging native binaries in .NET: https://github.com/dotnet/docs/blob/master/docs/core/tutorials/libraries.md#how-to-use-native-dependencies

Would you plan to target [.NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/)  1.5?

**Comment by SamuelEnglard** [comment]
I'd try to target as low as I can, so hopefully 1.3.

**Comment by mms-** [comment]
If you can use help testing the c# wrapper let me know!

**Comment by nathanaeljones** [comment]
BTW, I'm happy to write the P/Invokes if that would help. It's reasonably trivial for me - the non-trivial bits are tooling/packaging/CI/release/scripts due to the cognitive space and context switching required.

If you want, the low-level bindings (and perhaps JSON (de)serialization schema/classes) could even go in this repo, under bindings/dotnet, so that they can be tested against each release. (Can the .NET Core tooling fit in 100MB? I could install it on the docker containers.)

**Comment by SamuelEnglard** [comment]
My thinking/hopping is to have the P/Invoke and JSON (de)serialization code generated by T4 or [Scripty](https://github.com/daveaglick/Scripty). That way as you make changes they are updated with no issue.

The Core tooling should, really depends on the size of our dependancies

**Comment by nathanaeljones** [comment]
P/Invoke is easier by hand. I've invested incredible amounts of time into trying to automate that stuff - CppSharp, SWIG, and at least six others. There's just too much loss of information to make it work. 

As far as JSON serialization, the easiest path would probably be to find something that works similar to Serde.rs and duplicate the types. Serde can't generate schemas or Swagger or anything yet, so my  instinct would be to set up roundtrip tests between C# and Rust to ensure nothing is lost.

**Comment by SamuelEnglard** [comment]
I only plan to automate the functions themselves. The structs and such I'd write by hand.

I plan to use JSON.NET under the hood, but for the best performance I don't want to use the reflection API.

**Comment by nathanaeljones** [comment]
> I only plan to automate the functions themselves. The structs and such I'd write by hand.

Do you need me to make a C header file? What's the expected input and tool?

> I plan to use JSON.NET under the hood, but for the best performance I don't want to use the reflection API.

Fair enough. I don't think reflection can handle discriminated unions in C# anyway (just F#) - so code generation might come in handy there.

**Comment by nathanaeljones** [comment]
I was overthinking this. C# needs to do very little parsing. Primarily, it needs to serialize - which is easier. 

I could expose a 'mirror' API that just parses and re-serializes. If we disable whitespace and have the same rules for empty field omission, then it should be easy to compare the strings and verify that Rust is actually seeing everything that C# is sending. Thoughts?

**Comment by nathanaeljones** [comment]
Docs moved to: https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/imageflow/index.html

**Comment by SamuelEnglard** [comment]
> Do you need me to make a C header file? What's the expected input and tool?

A C or even C++ header would be easiest to work with. The easiest tool to work with would be the [P/Onvoke Interop Assistant](http://clrinterop.codeplex.com/releases/view/14120). It's not perfect in its generation but put its output is a good starting point.

> Fair enough. I don't think reflection can handle discriminated unions in C# anyway (just F#) - so code generation might come in handy there.

Not sure myself so a good point.

**Comment by nathanaeljones** [comment]
Here's a C header: https://gist.github.com/nathanaeljones/74f58b2d3aee3831eb3efdd316db77e0

All 4 structs are opaque. Keeping track of 4 kinds of pointers isn't hard, but I discovered today that P/Invoke supports typed pointers via `unsafe struct`. http://www.codeproject.com/Articles/339290/PInvoke-pointer-safety-Replacing-IntPtr-with-unsaf

Also, good reference on GC/Pinvoke race conditions: https://blogs.msdn.microsoft.com/bclteam/2005/03/15/safehandle-a-reliability-case-study-brian-grunkemeyer/ I like GC.KeepAlive() for it's explicit handling of the issue.

I don't have the interop assistant handy - can you let me know what that header file produces?

**Comment by SamuelEnglard** [comment]
I personally create structs that wrap the pointers usually, since it removes the need for unsafe and can have helper code.

I had to modify the header file slightly for the tool to be happy. Two issues where that I didn't have the imports for the int types (so I just stubbed them) and that just doing empty struct declarations is not enough for it (so I just typedef-ed them as `void*`). The modified header and output are [here](https://gist.github.com/SamuelEnglard/557c7b549a2a30a245a1b8a21fd9d2a7)

**Comment by nathanaeljones** [comment]
It looks like we're getting "ref IntPtr". Any idea why? Typedef? I can fully erase the types if you want.

**Comment by SamuelEnglard** [comment]
I made the structs `void` instead of `void*` and that got fixed. Updated the gist

**Comment by nathanaeljones** [comment]
I've added automatic header generation as part of the build process. Here's one with types erased: 

https://gist.github.com/nathanaeljones/023fe6f3e271d6e72cf0b8c3de5013b2

**Comment by SamuelEnglard** [comment]
As I'm going through the C header I have some questions.

Why do you use `uint8_t` in some locations for strings and in others `char`, what's the logic here? Trying to figure out how to marshal and how to deal with on the C# side.

**Comment by SamuelEnglard** [comment]
Another question: What will be the name of the native library? The file.

**Comment by nathanaeljones** [comment]
imageflow.dll on windows, libimageflow.so and libimageflow.dylib
elsewhere.  Dllimport "imageflow" should work.

The latest AppVeyor build should have a working imageflow.dll

**Comment by SamuelEnglard** [comment]
>imageflow.dll on windows, libimageflow.so and libimageflow.dylib
elsewhere.  Dllimport "imageflow" should work.

>The latest AppVeyor build should have a working imageflow.dll

Thanks. And my other question?

**Comment by nathanaeljones** [comment]
It should only be relevant for C users; treat all strings and buffers as
unsigned byte arrays.

**Comment by SamuelEnglard** [comment]
> It should only be relevant for C users; treat all strings and buffers as
unsigned byte arrays. 

Ok. And strings are encoded as?

**Comment by nathanaeljones** [comment]
UTF-8/ASCII - everywhere except for `imageflow_io_create_for_file`, where filename needs to be the operating system code page used for fopen. 

I'm writing some clarifications on strings. i8/u8/libc::c_uint8_t/libc::c_int8_t/libc::c_char are all signature compatible, but I didn't offer enough detail. 

Unless there's a corresponding length, assume null-termination for strings in either direction. `imageflow_context_error_and_stacktrace` is the only function that both returns the length and writes a null-character/

**Comment by nathanaeljones** [comment]
Also, Happy Thanksgiving!

**Comment by SamuelEnglard** [comment]
>Also, Happy Thanksgiving!

Thanks, you too!

**Comment by nathanaeljones** [comment]
New ABI docs are uploading. c_char should now be used more consistently for null-terminated strings, u8 for length-only strings.  UTF-8 except for the OS filename in `imageflow_io_create_for_file`.

**Comment by SamuelEnglard** [comment]
Thanks. Makes that much easier to understand. Doing length only will be a pain in C# but can be done

**Comment by SamuelEnglard** [comment]
Are all jobs blocking?

**Comment by nathanaeljones** [comment]
Currently only the calling thread is used.

**Comment by nathanaeljones** [comment]
Yes. No async in 1.0.

**Comment by SamuelEnglard** [comment]
Ok, simple enough.

**Comment by SamuelEnglard** [comment]
`JobIO` is a struct based on the Header but docs say it's an enum?

**Comment by nathanaeljones** [comment]
The name is currently overloaded; it's an opaque pointer. (Also, Rust enums
are unions, not c enums)

**Comment by SamuelEnglard** [comment]
> The name is currently overloaded; it's an opaque pointer.

That works

> (Also, Rust enums are unions, not c enums)

As the Header has them as enums I can treat them as such?

**Comment by nathanaeljones** [comment]
Rust enums annotated with #[repr(C)] are C enums; others are struct
unions-ish. The header file is perfectly correct, but the docs categorize
by Rust terms instead of C. I may have a fix for this.

**Comment by SamuelEnglard** [comment]
Or at least document "correction"

**Comment by nathanaeljones** [comment]
Should be improved: https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/imageflow/index.html

**Comment by SamuelEnglard** [comment]
Much clearer! Thanks.

May I suggest removing the C#/.NET references for how things work? While great for me, developers writing bindings for other languages might not get them and be confused.

**Comment by nathanaeljones** [comment]
I will definitely do that when we get other languages going. 

I've just finished getting imageflow_tool.exe into a 'playable' state. Latest artifacts at https://ci.appveyor.com/project/imazen/imageflow

`imageflow_tool examples --export-build-examples=all` will create an examples folder with some scripts to run. 

Would you mind giving that a look? I've written the last 4kloc on < 4hrs sleep, and would like another set of eyes on the tool before I publish the update.

**Comment by SamuelEnglard** [comment]
I'll give it a try ASAP

**Comment by nathanaeljones** [comment]
Usability feedback also good. I.e, I should probably change `examples --export-build-examples=all` to `examples --generate`, eh?

**Comment by SamuelEnglard** [comment]
Yeah

**Comment by nathanaeljones** [comment]
Done. Thoughts? https://github.com/imazen/imageflow/releases/tag/v0.0.7

**Comment by nathanaeljones** [comment]
I'm setting up testing of bindings (where sufficiently quick) under the main CI. I'd like to figure out if C# would work in that env. Do you have a stub repo/empty project demoing the tools you'd need?

**Comment by nathanaeljones** [comment]
I'm going to put the latest ubuntu package - `dotnet-dev-1.0.0-preview2.1-003177` in the docker instances; they're a pain to change, and it *should* work.

**Comment by SamuelEnglard** [comment]
Been busy so I haven't had the time to work on this the past week. I should push my branch this weekend, though it's mostly pure interop code right now.

**Comment by SamuelEnglard** [comment]
Is there (or will there be) a JSON schema for the JSON requests/responses?

**Comment by SamuelEnglard** [comment]
I'm noticing things moving from `imageflow` to `imageflow_core`...?

**Comment by nathanaeljones** [comment]
Right now I don't have an automated way to generate a schema; the generated examples should always be correct, though. 

What do you mean re: imageflow -> imageflow_core? I'm still porting C from imageflow_c to imageflow_core, but this shouldn't change anything ABI-wise - the ABI is already Rust.

**Comment by SamuelEnglard** [comment]
> Right now I don't have an automated way to generate a schema; the generated examples should always be correct, though.

I'll generate from the examples then for now.

> What do you mean re: imageflow -> imageflow_core? I'm still porting C from imageflow_c to imageflow_core, but this shouldn't change anything ABI-wise - the ABI is already Rust.

https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/imageflow/struct.Job.html moved to https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/imageflow_core/struct.Job.html

**Comment by nathanaeljones** [comment]
Yeah, Job became a native Rust object (no longer a C thing). Still an opaque pointer. That's actually not why the docs changed; that was because I forgot something when I did that refactor (all re-exported types from a crate should show up in docs; they are duplicated between crates. Fixing..

**Comment by SamuelEnglard** [comment]
Ah, ok. Just trying to make sure I'm replicating the API correctly :)

**Comment by SamuelEnglard** [comment]
Initial commit https://github.com/imazen/imageflow/tree/dotnet/bindings/dotnet/Imageflow

**Comment by nathanaeljones** [comment]
Thanks! I've merged it to master. I'd like to contribute some unit and integration tests. Do you like xUnit?

**Comment by nathanaeljones** [comment]
Apologies that I didn't have .gitattributes and .editorconfig set up for .xproj and .json files; I've fixed that now. You may have to delete and re-clone (or temporarily delete bindings/dotnet) from your working directory to avoid bugs in older versions of Git. 

After that there shouldn't be any more line-ending pain. If you have the EditorConfig plugin for your text editor(s)/ides, there shouldn't be any churn whatsoever in your local diffs, either.

**Comment by SamuelEnglard** [comment]
I have no issues with xUnit, though unit testing right now will be hard since there is very little functional code. It's mostly just pure P/Invoke code.

And no issue. I'll install the plugin.

**Comment by SamuelEnglard** [comment]
How do we want to handle .NET documentation?

**Comment by nathanaeljones** [comment]
I've used Doxygen, Docu, and worked on a few different tools to try to blend generated API docs and prose well. Nothing really came to fruition. If you have a favorite tool, let's use that.

**Comment by nathanaeljones** [comment]
My only requirement would be that we can generate and upload from CI - so it would need a command-line tool. 

It looks like Microsoft has moved to using DocFX: https://dotnet.github.io/docfx/ for ASP.NET Core, at least: https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md 

I haven't used it, but it [seems less painful](https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project_2.html) that others I've worked with.

**Comment by SamuelEnglard** [comment]
Could be bias on my part but SandCastle seems way easier

**Comment by nathanaeljones** [comment]
It's officially abandonware, but if you're willing to maintain it on CI, then I'm okay with it. Can we keep the run times under 2 minutes? Running it on ImageResizer was about 45 mins/build, for about 20kloc (at the time). Roughly 60 seconds per class. I'd hope it's faster now?

**Comment by SamuelEnglard** [comment]
From Microsoft yes, but the community has picked it up https://github.com/EWSoftware/SHFB

**Comment by SamuelEnglard** [comment]
Pushed to the `dotnet` branch an update that should build documentation using SandCastle

**Comment by nathanaeljones** [comment]
Could you rebase against master? `dotnet` is 175 commits behind. I've merged previous commits into master, but I didn't want to overwrite your branch.

**Comment by SamuelEnglard** [comment]
Will do when I get home from work!

**Comment by SamuelEnglard** [comment]
Done, though good lord did git fight me!

**Comment by nathanaeljones** [comment]
Yeah, if I merge into master but you don't pull, then you have to redo it
all and it can be worse the second time....

**Comment by SamuelEnglard** [comment]
I did pull but git kept seg faulting!

**Comment by nathanaeljones** [comment]
Git doesn't handle line ending changes well on windows... thus the need for
delete/clone after changing .gitattributes

**Comment by SamuelEnglard** [comment]
ah

**Comment by nathanaeljones** [comment]
I have some info on packaging. It looks like Nuget 3.5 offers runtimes support. 

I imagine we would set up a separate repository like https://github.com/natemcmaster/libsqlite3-package to fetch and combine the binaries. 

Related:
http://www.natemcmaster.com/blog/2016/05/19/nuget3-rid-graph/
https://github.com/aspnet/dnx/issues/402

If the SQLlite package works smoothly on .NET Core and .NET 4.6 in our testing (VS 2015.3 and command line), then I'd say we can just do what they're doing. 

Caveat: Debug symbols (10-22mb+), but necessary for stack traces.  On Windows, these are separate (.pdb), and we could probably publish a separate package for them, but on linux/osx, they're currently combined.

**Comment by SamuelEnglard** [comment]
I'm thinking of removing the dotnet branch and just using branches for each change?

**Comment by nathanaeljones** [comment]
Good idea; I did merge it in a few days ago, but shorter-lived branches are
best.

**Comment by SamuelEnglard** [comment]
Will do!

**Comment by SamuelEnglard** [comment]
Pushed how I'm thinking of parsing IoEnum. Thoughts?

**Comment by nathanaeljones** [comment]
It looks good to me. I really couldn't offer you any advice as far as performance goes without running profiling on it, and I'm not familiar with the latest JSON serialization techniques. You're definitely more qualified here. 

I'll keep an eye on what you push and let you know if I see anything that looks problematic given current or future API plans.

**Comment by SamuelEnglard** [comment]
Was more worried about my understand of the JSON format than performance.

**Comment by nathanaeljones** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by SamuelEnglard** [comment]
Yeah, I saw. Two people brought us up in the comments

**Comment by CShepartd** [comment]
VS17 RTV and .Net Core Tools 1.0 are already released so maybe its time to migrate wrapper to MSBuild and Csproj?

**Comment by SamuelEnglard** [comment]
> VS17 RTM and .Net Core Tools 1.0 are already released so maybe its time to migrate wrapper to MSBuild and Csproj?

That's my weekend plan!

**Comment by nathanaeljones** [comment]
Woot! This is still under development: https://github.com/jaredpar/pinvoke

Also, the integration server is now running RTM 1.0.

**Comment by SamuelEnglard** [comment]
@nathanaeljones That's awesome!

**Comment by nathanaeljones** [comment]
I'd like to spike a partial wrapper for Imageflow that doesn't do any abstractions at the P/Invoke layer, but just uses IntPtr. Do you have the raw output from a P/Invoke generation tool handy?

**Comment by SamuelEnglard** [comment]
Not home tonight but tomorrow night I should be able to get that to you 👍

**Comment by SamuelEnglard** [comment]
About two months late but... https://gist.github.com/SamuelEnglard/557c7b549a2a30a245a1b8a21fd9d2a7
Includes C# and the C header used

**Comment by RossLieberman** [comment]
Thanks @SamuelEnglard . I was curious on the project and checked in yesterday and saw there wasn't much movement lately. I'm interested in these C# bindings you've been working on. I wish I had time to test or help out. But I'm happy to see your commit.

**Comment by SamuelEnglard** [comment]
@RossLieberman Yeah... Massive shake ups at work have me falling behind on lots of stuff. Finally trying to get back into it

**Comment by CShepartd** [comment]
Thanks @SamuelEnglard

**Comment by SamuelEnglard** [comment]
@CShepartd planning on publishing to NuGet once their is a public API. The current code is all internal. Can't really give a time line on that.

**Comment by nathanaeljones** [comment]
@SamuelEnglard Thank you, but that's not the right header; you should be using https://github.com/imazen/imageflow/blob/master/bindings/headers/imageflow_pinvoke.h

**Comment by SamuelEnglard** [comment]
@nathanaeljones I had feeling it wasn't but figured better try and redo. Leaving work now, when I get home I'll regenerate (and check the primary libraries signatures)

**Comment by SamuelEnglard** [comment]
@nathanaeljones Updated the gist

**Comment by OpenSpacesAndPlaces** [comment]
@SamuelEnglard What's the best path for using this in a .Net Core app in the meantime?
We're converting over a .Net Framework CMS to .Net Core, and we used ImageResizer pretty extensively.

I expect until this becomes more official I'll at least need to create some kind of routing rules/middleware on my own - no worries there.

I was able to take the binding work here, target .Net 2.0 Core Preview 2 - and then create my own local nuget package for import. That all worked fine:
https://github.com/imazen/imageflow/tree/master/bindings/dotnet/Imageflow

As you've already mentioned, and I've seen in the source - the C# bindings don't seem to have any publicly exposed methods. In destination project I'm not able to-do anything besides see the namespaces exist effectively.

I don't have an issue with having to-do build out to make this work, but I'm trying to avoid unnecessary work and/or false starts. 

Thanks in advance for the help!

**Comment by SamuelEnglard** [comment]
@OpenSpacesAndPlaces your best bet at this time is to use the HTTP server (imageflow_server) for now. It's not the best solution but for a CMS that should work.

**Comment by SamuelEnglard** [comment]
As a general update:

Current issue I'm dealing with is how to work with images embedded in the JSON stream. Since one of the big goals of imageflow is performance I do not want to do it the quick and easy way. Right now that means I may have to write my own JSON parsing system. Obviously don't want to do that so been playing around trying to see what options I have.

My goal for the C#/.NET bindings is that .NET users can use this with no understanding of native code ideas. That means lots of wrapping logic. As noted, the current code is all the raw wrappings, P/Invoke code that I do not want end users to deal with. I am going to abstract that away with more .NET styled APIs.

**Comment by nathanaeljones** [comment]
Maybe we should table implementing embedded images, and assume that we'll use the job api instead of the build api (the job api takes pointers to buffers).

**Comment by SamuelEnglard** [comment]
That's been one thought I had as well. I may just do that

**Comment by nathanaeljones** [comment]
I think it's very acceptable for 1.0 to only support byte arrays for input and output.

**Comment by CShepartd** [comment]
I had the same problem like @OpenSpacesAndPlaces and give up with ImageFlow and created own multiplatform P/Invoke wrapper of FreeImage (based on https://github.com/matgr1/FreeImage-dotnet-core). I needed only resize images and working well

**Comment by nathanaeljones** [comment]
Today I wrote a minimal C# wrapper for Imageflow: https://github.com/imazen/imageflow/tree/master/bindings/dn

This exposes both the JSON graph API and the ImageResizer4 quersytring API. 

@CShepartd I'm sorry that imageflow has been disappointing for you. Is this primarily about the C# wrapper, or do you have concerns about the project itself? We do have a roadmap, and bugs are to be expected. We anticipated that more people would give imageflow a try and provide feedback, but that volume has been extremely low.

**Comment by nathanaeljones** [comment]
Note: https://github.com/imazen/imageflow/commit/970042105bcbe2af70ac4a9c29d440474a20a8fe

* Modify signature of imageflow_io_create_for_file(context, mode, filename) -> * imageflow_job_io (Remove imageflow_cleanup_with parameter)
* Modify signature of imageflow_io_create_from_buffer(context, buffer, buffer_byte_coutn, lifteime) (Remove imageflow_cleanup_with parameter)
* Remove CleanupWith enumeration (Just don't reuse contexts much)
* Mark  imageflow_context_error_code(context) as unstabilized (don't depend on this)
* Remove imageflow_context_raise_error (no usage scenario)
* Remove imageflow_context_add_to_callstack (no usage scenario)
* Remove imageflow_context_clear_error(context) -> void (replaced with try_clear)

Improvements to ABI
* Add panic recovery to all methods
* Add null-parameter checking to all methods
* And most-significant-bit checking (for size_t) to all methods
* Add imageflow_context_error_as_exit_code(context) -> i32 (and stabilize values)
* Add imageflow_context_error_as_http_code(context) -> 32 (and stabilize values)
* Add imageflow_context_error_try_clear(context) -> bool
* Add imageflow_context_error_recoverable(context) -> bool

**Comment by nathanaeljones** [comment]
Quick, any reason not to merge context and job? Contexts are smaller/quicker now. JobContext would be simpler. Io objects would get an io_id upon creation.  

Can you think of any use case that would suffer from this change?

/cc: @SamuelEnglard

**Comment by SamuelEnglard** [comment]
Nothing off the top my head

**Comment by nathanaeljones** [comment]
Thoughts on this API? 

```c
bool imageflow_abi_compatible(uint32_t imageflow_abi_ver_major, uint32_t imageflow_abi_ver_minor);

uint32_t imageflow_abi_version_major(void);

uint32_t imageflow_abi_version_minor(void);

void* imageflow_context_create(uint32_t imageflow_abi_ver_major, uint32_t imageflow_abi_ver_minor);

bool imageflow_context_begin_terminate(void* context);

void imageflow_context_destroy(void* context);

bool imageflow_context_has_error(void* context);

bool imageflow_context_error_recoverable(void* context);

bool imageflow_context_error_try_clear(void* context);

int32_t imageflow_context_error_code(void* context);

int32_t imageflow_context_error_as_exit_code(void* context);

int32_t imageflow_context_error_as_http_code(void* context);

bool imageflow_context_error_write_to_buffer(void* context, char* buffer, size_t buffer_length, size_t* bytes_written);

bool imageflow_context_print_and_exit_if_error(void* context);

bool imageflow_json_response_read(void* context, void const* response_in, int64_t* status_as_http_code_out, uint8_t const** buffer_utf8_no_nulls_out, size_t* buffer_size_out);

bool imageflow_json_response_destroy(void* context, void* response);

void const* imageflow_context_send_json(void* context, char const* method, uint8_t const* json_buffer, size_t json_buffer_size);

bool imageflow_context_add_file(void* context, int32_t io_id, imageflow_direction direction, imageflow_io_mode mode, char const* filename);

bool imageflow_context_add_input_buffer(void* context, int32_t io_id, uint8_t const* buffer, size_t buffer_byte_count, imageflow_lifetime lifetime);

bool imageflow_context_add_output_buffer(void* context, int32_t io_id);

bool imageflow_context_get_output_buffer_by_id(void* context, int32_t io_id, uint8_t const** result_buffer, size_t* result_buffer_length);

void* imageflow_context_memory_allocate(void* context, size_t bytes, char const* filename, int32_t line);

bool imageflow_context_memory_free(void* context, void* pointer, char const* filename, int32_t line);
```

**Comment by nathanaeljones** [comment]
Implemented.

**Comment by SamuelEnglard** [comment]
Looks good to me

**Comment by nathanaeljones** [comment]
@SamuelEnglard I'm planning to move the new .NET bindings to their own repository (We now have a versioned ABI, and a separate repo allows for a much quicker release cycle for the bindings). 

To reduce confusion I'd like to move your bindings elsewhere as well.

**Comment by nathanaeljones** [comment]
The bindings are now on NuGet https://www.nuget.org/packages/Imageflow.Net/
You must also install the correct Imageflow.NativeBindings package
https://www.nuget.org/packages?q=Imageflow.NativeRuntime


The project has been moved to https://github.com/imazen/imageflow-dotnet 
The plan is to test the latest version of the bindings from the Imageflow CI, but allow the bindings a faster test/release cycle (2-minute CI builds instead of 60m).

**Comment by nathanaeljones** [comment]
Please test out Imageflow.Net and provide feedback at  https://github.com/imazen/imageflow-dotnet/issues
