### ISSUE TITLE
Designing continuous integration

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#73]
**Update [continuous-integration.md](https://github.com/imazen/imageflow/edit/master/continuous-integration.md) as this progresses**
# Designing continuous integration for Imageflow
### category A platforms

These are the platforms we build on. All are 64-bit, but may or may not compile/test in 32-bit compatibility as well.

These 8 platforms must also be tested against Rust nightly in order for end-to-end valgrind to work. 16 permutations is not practical for every commit to master; we must reduce this.
- Windows 2012 R2 with VS2015 (As configured on [AppVeyor](https://www.appveyor.com/docs/installed-software) when using `os: Visual Studio 2015`). We cross-compile 32-bit, and run 32-bit tests as well, but as a separate job. 
- OS X 10.10 with xcode 7.1.1 and OS X 10.11 with xcode 7.3. These correspond to `xcode7.1` and `xcode7.3` on [travis's OS X environments](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version). [xcode8beta4 has been dropped from matrix for now](https://github.com/imazen/imageflow/commit/758e87d07418c693e57c233dbb6028df62fa53ae).
- 64-bit Ubuntu Xenial/GCC5.3, wily/gcc5.2, trusty/gcc4.8, vivid/gcc4.9, currently using [these docker images](https://github.com/lasote/conan-docker-tools). 
### category B platforms

These are the platforms we target compatibility with:
- 32-bit and 64-bit Windows Server 2012 R2, Windows Server 2016, Windows 10
- 64-bit OS X 10.10 and 10.11 
- 64-bit Ubuntu 12.04, 14.04, 14.10, 16.04. We upload a universal binary from one docker instance [verified with AppChecker](https://wiki.linuxfoundation.org/lsb/all-about-linux-application-checker), which in theory should ensure binary (symbol table) compatibility on all major distributions. 
### Primary goals
- Run all tests in both C and Rust code, on all category A platforms, providing clear failure detail for local repro. 
- Create binaries for Linux, Mac, and Windows, upload them somewhere, and update something to link to them. 
- Binaries include (flow-proto1, imageflow-tool*, imageflow-server*, libimageflow* (cdylib), libimageflow* (static lib))
- Our binaries should be fast. Released binaries should target the best instruction sets possible.
- We should test all code paths with valgrind
- We should calculate test coverage for both Rust and C (coveralls/lcov) parts of the code.
- We should compile using both Stable and Nightly rust
### Secondary goals
- Generate documentation and publish to two locations/channels - stable and nightly. 
- Versioned stable releases and documentation sets should be accessible indefinitely. 
- We should push our Rust packages to Crates.io
- We should push our cdylibs to Conan.io for C/C++ consumers, and NuGet* for .NET consumers. (both stable and nightly channels)

Items with a star are blocked, but are expected to be unblocked. 
### Constraints
- In order to use Valgrind on Rust executables or tests (as jemalloc [dropped valgrind support](https://github.com/jemalloc/jemalloc/issues/369)) , one must use the [nightly version of the Rust compiler (possibly built with custom flags)](https://github.com/rust-lang/rust/issues/28224#issuecomment-138725566), or expose the tests as a static library (system allocator) which is invoked by a C wrapper executable.  
- Docker can only be used on x64 Travis. 
- We must test against both Rust nightly and Rust stable. 
### Acceptable compromises
- We can target a base assumption of AVX & SSE4.2 instruction support for public binary releases. Old (2008-era) and cheap < $50 CPUs may not support these, but we can also say that.
- No 32-bit artifacts for linux
- No 32-bit artifacts for mac
- No ARM builds
- No testing of mingw/gcc on Windows; MS CRT only.
- Security through obscurity for binaries during the Kickstarter early access period. 
- To reduce permutations, we can skip testing against the Rust Beta channel, although we shouldn't.
- We can move particularly slow things (like valgrind testing) to be conditional upon branch name, and create a branch 'slow-tests' which we push to manually, periodically.
### Resources
- AppVeyor has described a method for [deploy.yml](https://www.appveyor.com/blog/2015/11/04/deployment-projects) in order to separate test and deploy jobs. This means a separate status badge for 'successfully deployed' can be used, since you use a separate branch to trigger said deployment.

**Comment by nathanaeljones** [comment]
In addition to a master branch(nightly channel) and stable channel, we also want a channel to which we perform additional testing (coverity, valgrind), and a channel from which we deploy a demo server. 

Branches:

* master
* stable
* scan
* demo-deploy

**Comment by SamuelEnglard** [comment]
> No testing of mingw/gcc on Windows; MS CRT only.

What about [Clang with Microsoft CodeGen](https://blogs.msdn.microsoft.com/vcblog/2015/12/04/clang-with-microsoft-codegen-in-vs-2015-update-1/)?

**Comment by memsharded** [comment]
IMHO, Clang on win is still quite experimental, I would say very rarely used in production. Moreover, even MinGW share under windows is quite low compared with MSVC. I would bet that if someone is using Win as production platform, they are also using MSVC, so for me, doing CI in Win with MSVC only is a good enough setting.

**Comment by SamuelEnglard** [comment]
No argument there @memsharded, more just wanted us to have an "official" stance. Better to decided now than be caught off guard later.

**Comment by memsharded** [comment]
Sure, just trying to provide my 2 cents, about what I know about C/C++ compilers usage in different platforms.

**Comment by nathanaeljones** [comment]
We have to be very careful about adding new build permutations. We're currently looking at 18 jobs per commit, and that introduces impractically high latency into the development cycle (we can only practically run the test suite on the OS currently used for development, so compiler/OS differences are common and usually caught by CI. 

We may set 'master' to only test one permutation for each platform, but have stable/scan branches test all 18.

**Comment by nathanaeljones** [comment]
Here's the shortened list planned so far:

* gcc5.4/xenial + rust stable + coveralls
* gcc5.4/xenial + rust nightly + valgrind
* osx/10.11 + apple-clange 7.3 + rust stable
* gcc4.8/trusty + rust stable
* gcc4.9/vivid + rust stable
* WS2012 R2 x64 + rust stable
* WS2012 R2 x86 + rust stable

This may turn out to be fast enough that multiple batches of jobs don't have to be queued.

**Comment by nathanaeljones** [comment]
I also got Xcode 8 beta 6 working. Unfortunately, travis only does 5 concurrent jobs, and having both xcode 7.3 (10.11) and xcode (8 beta 6) 10.11 effectively doubles CI time. Does anyone feel there is a concrete need for both? If not, should I prefer the stable xcode release?

**Comment by nathanaeljones** [comment]
@SamuelEnglard AFAICT, Clang actually binds to the MSVCRT, as it uses MSFT codegen, so all you would need to do if that support was important for you:

* Track down the CMake configuration/plugin/version required to generate (and execute/link) project files compatible with that tool-chain. 
* Add a 3rd permutation to AppVeyor. I'm okay with 3 tasks per commit there, as we're under 30 mins per build at the moment. I would probably stick with just 64-bit, though. 

I just might have to turn it off at points if it becomes problematic; it couldn't be a guaranteed Cat A platform given my resource constraints and the preview nature. Right now I'm not aware of any perf advantages over MSVC, just better syntax compatibility with mainstream compilers. Which is wonderful, but we can't rely on it until it becomes a bit more mature and contributors seem OK with wrangling that VS plugin set.

---

Has anyone used PGO much? I'd like to track down an example of AppVeyor PGO-during-CI and integrate that, as MSVC perf out of the box is ... lacking compared to gcc or clang.

**Comment by SamuelEnglard** [comment]
@nathanaeljones 

> better syntax compatibility with mainstream compilers

That is the only reason I care, since it would make our lives easier. I do admit that for now we can ignore it as it's not all that mature or well known.

**Comment by nathanaeljones** [comment]
Targeting additional architectures (haswell, sandy bridge) took priority over testing gcc 4.9. We now provide binaries for the following platforms: 

* GCC 4.8 on Ubuntu 14.04
* GCC 5.4 on Ubuntu 16.04 Xenial. 
* XCode 7.3 on OS X 10.11 
* Windows Server 2012 R2 (32 and 64-bit) 

Closing this; unexpected constraints will mean this list may shift over time.
