### ISSUE TITLE
Build/find Rust gif codec

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#80]
Needs:
- Animated gif decode (and encode!) support. Remember that animated gifs can use frame-by-frame deltas in two ways - one, by only including a subset of the global canvas (i.e, left,right offset and smaller width/height for frame), and two, by using transparent pixels. 
- GIF87 and 89a support. 
- Decent test suite.

Prior art:
https://github.com/pcwalton/rust-media/blob/master/containers/gif.rs
https://github.com/PistonDevelopers/image-gif

**image-gif** is very promising. We should try wiring it up to Imageflow.

**Comment by stonetip** [comment]
We never use GIFs and have used 8 or 24-bit PNGs (or SVGs) for a long time now. For the first time in a few years, I actually made an animated GIF the other day (comparing two maps) and despite Photoshop's best optimizations it was 7 Mb! I ended up sending a 784K MPEG instead. What's important to us is photographic and aerial/remote sensing imagery - balancing the best, sharpest images with the smallest file sizes, processed as quickly as possible.

**Comment by Charmatzis** [comment]
Well done, that's great news for the GIS community!

**Comment by SamuelEnglard** [comment]
Annoying enough in GIS we are stuck sometimes with GIFs over MPEG (and the like) so imageflow having support for GIF would be great.

**Comment by nathanaeljones** [comment]
Gif read/write is implemented (not animated yet, though)
