### ISSUE TITLE
Allow copying of static strings (file and function names)

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#81]
Some languages may not have the ability to create static-lifetime CStrings in a reasonable way. 

For these languages, a boolean flag, 'copy_strings', should be provided. 

As error reporting methods should not allocate, we need to use pre-allocated space. Remaining space in the error message buffer may be used, but languages with this need should also inform the context of their need ahead of time, so that additional space can be allocated. 

This is of particular concern for methods 
- `imageflow_context_add_to_callstack`
- `imageflow_context_raise_error`

But also for all allocation methods, which have not yet been exposed.

**Comment by SamuelEnglard** [comment]
So we have an issue internally which the error message for is a static CString. The issue is that when it's passed to language X we don't want it to copy/allocate?

**Comment by nathanaeljones** [comment]
Correct, as out of memory conditions should be gracefully handled - we
currently pre-allocate 2kb space for the message, but not an extra 8kb for
the stack trace - just 300bytes for pointers to static strings for file and
function names.

**Comment by nathanaeljones** [comment]
This only applies to Filenames C strings; we already have a mutable buffer for error messages. 

For filenames, I think we should consider handling this in C# until v2, where I will hopefully rewrite the Context in Rust (everything else has been ported already). My initial approach:

1. C# Context object contains a hidden Dictionary<String, GCHandle>. 
2. The Context method that reports the error or adds to the stack trace can use [`[CallerFileName] and [CallerLineNumber]`](http://stackoverflow.com/a/16295463/166893)
3. The error/stacktrace method will *not* allocate if the error code == OOM.
4. The method will either lookup or create a new GCHandle via GCHandle.Alloc() on a CString representation (null-terminated) of the string in question, and add to dictionary to minimize pinned objects. (Given the rarity of error conditions, a List<GCHandle> might be better - caching is of questionable value).
5. And use GCHandle.ToIntPtr to provide it to the FFI call. 
6. C# Context object implements Dispose already; call  `.Free` on all values in the dictionary to unpin them from memory. 

Filename pointers aren't currently blocking Ruby or Rust, and this would entail refactoring a highly stable part of the codebase. 

Thoughts?

**Comment by SamuelEnglard** [comment]
Some questions to help me understand your idea:

1. C# Context is... ?
2. CString is a C# class?

**Comment by nathanaeljones** [comment]
The internet ate my reply.  From Oct 20 3:08pm:

> CString is a Rust class - any null-terminated byte array would be a a valid C String.
> 
> In the wrapper, you will need a Context class or its equivalent which implements IDispose and contains an IntPtr to the imageflow_context struct. Basically you'll need a container class of some kind - I call it Context.

**Comment by nathanaeljones** [comment]
CString is a Rust class - just a null-terminatd byte array.

In the wrapper, you will need to create a Context class or its equivalent
which implements IDispose and contains an IntPtr to the imageflow_context
struct.

**Comment by SamuelEnglard** [comment]
Ok, I'm not seeing how this solves the memory allocation issue. To show the file name to C# memory would be allocated. I could solve this I think. Let me experiment a bit.

**Comment by nathanaeljones** [comment]
It doesn't - you still have to allocate memory in C#. But you can pin that memory using GCHandle, which makes it safe to pass into the context until the context is gone. Given this only happens in a failure path, it's brief enough that I don't see a performance or GC or fragmentation downside.

**Comment by SamuelEnglard** [comment]
What I'm thinking though is I could allocate a large string. Every time we call I pin it during the call so I can pass it in and unpin after call.

**Comment by nathanaeljones** [comment]
The pointers are stored inside imageflow_context, as it stores the last exception and stacktrace. So they can't unpin until the context is destroyed.

**Comment by nathanaeljones** [comment]
Yep.

**Comment by nathanaeljones** [comment]
Closing as `wontfix` for now. Will reconsider for 2.0
