### ISSUE TITLE
Auto-deploy imageflow_server to Docker Cloud / DO

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#92]
As part of Travis CI build,
1. Copy imageflow_server _and_ test assemblies into new docker image. Dockerfile COPY cmd, etc.
2. Run tests within docker image to verify functionality.
3. Push docker image to docker cloud for auto-deploy to Digital Ocean cluster. 

Using a new docker image will reduce footprint from 1GB to 200mb. 

Phase 2:

Use Docker Compose; use Redis for caching.

**Comment by alexisvincent** [comment]
It would be awesome to get a docker image with an entry point set so that one can simply
`docker run imazen/imageflow start --port 80`.

Any chance of getting this?

**Comment by nathanaeljones** [comment]
If you want a HTTP2 nginx-proxied (but not output-cached) setup, this stackfile for Docker Cloud should work: `https://github.com/imazen/imageflow/blob/master/ci/docker/hub/proxied/stackfile.yml`. It automatically grabs you a certificate from letsencrypt, at the expense of 5minutes extra boot time.

For imageflow alone, `docker run imazen/imageflow_server_unsecured start --port 3000 --demo` works. It doesn't support HTTPS, though - not yet. And it's under a low-privilege user account, so you can run it on port 80.

**Comment by nathanaeljones** [comment]
Fixed. @alexisvincent - please open another issue for any questions related to the Docker image(s). Happy to help, but this task is **done**. :tada: 

Each commit to Imageflow triggers a rebuild of imazen/imageflow_base_os immediately. When all tests pass, a second Docker image is built - imazen/imageflow_server_unsecured. When this is updated, the demo server reloads the new code. 

For the moment, this demo server is reachable at https://imageflow-demo-a.imazen.io/proxied_demo/index.html  

Folks... yeah, I recycled the ImageResizer 2007-era demo page. Sue me. Or, help me update it and get free promotion for your web agency. The ImageResizer demo page was downloaded over a million times....

**Comment by alexisvincent** [comment]
Endpoint is down :)

**Comment by nathanaeljones** [comment]
Thanks! I got it back up Saturday, but I definitely need to add a monitoring solution.

**Comment by alexisvincent** [comment]
No worries. Just noticed :)
