### ISSUE TITLE
Consider hash-based caching

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#93]
https://libraries.io/cargo/twox-hash

**Comment by SamuelEnglard** [comment]
For?

**Comment by nathanaeljones** [comment]
Caching/Reusing parts of the operation graph across requests (given hashed
inputs).  50% of cost is decoding jpeg data. If a subset of the graph is
requested repeatedly, the uncompressed data could be cached. Particularly
helpful for watermarks, but likely to end up as a set of optional
heuristics.

**Comment by SamuelEnglard** [comment]
I think then this could/should be exposed to the API as well, since users would know what could be cached saving us work
