### ISSUE TITLE
Collect 'challenging' images and tasks

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#98]
We want

1. Verified valid images that tend to fail with Imageflow or other tools. 
2. JSON tasks that are complex and unexpected
3. Sets of (input/task/expected output) triples that meet the above criteria, or fail with other tools. Having an expected result on file makes things much easier to fix. 

### Minimize file size

1. Try to use the smallest dimensions possible to reproduce the problem. We can test 50x more scenarios if our file sizes are small.
2. Try to eliminate image data - drawing a rectangle over the bitmap, but preserving the metadata/dimensions/ICC that are problematic. If the problem is around color interpretation, you may need several rectangles to demonstrate the problem. This is extra work, but simultaneously minimizes compressed image size and fixes the hardest problem - copyright.

### Copyright

If we're hosting/copying/displaying regression tests involving images you send us, we need to have the legal right to do so.

If you can't get the right to release the images involved under the Apache(Imazen) Contributor Agreement (or under some MIT-compatible license, or public domain), then you may consider drawing a  rectangle over the images in question, but preserving the metadata, dimensions, and ICC profile that are likely to be the source of the problem. Do inspect the metadata for potentially copyrightable material, but it's kind of unlikely (Excluding the "Copyright" string itself). 

### How to share them

For now, attach them to this issue via comment and drag/drop. We need a better tool for collecting these, but this will do for now. 10MB limit on image size, 25mb limit on zip file size.

**Comment by token97** [comment]
Hey,
Enclosed, an image that can't be read by imageflow.  I tried with imageresizer, it's works well.
![img_compression_5](https://user-images.githubusercontent.com/8781331/30689048-1b0ce492-9ec0-11e7-940f-b20cece122d1.jpg)
