### ISSUE TITLE
RFC: Switch JSON API from camelCase to snake_case

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#99]
Rust forces use of snake_case for member names and functions. We can (and currently) map most things to custom strings, but it increases human error and inconsistency.

Java, PHP, and Javascript have a camelCase convention for members/functions. C# does not. Ruby/Perl/Python/Elixr/C++ and Rust use snake_case. 

Reducing renaming/mapping on both client and server is a goal. snake_case also sidesteps inconsistent conventions around capitalization of acronyms. 

While camelCase is a Javascript convention, we expect more Imageflow usage outside of Javascript and Java  than with them them.

Am I overlooking any good arguments for remaining with camelCase?

http://stackoverflow.com/a/25368854/166893

**Comment by SamuelEnglard** [comment]
Are you referring to Functions or JSON objects?

**Comment by nathanaeljones** [comment]
json keys and the client wrapper properties/methods they would correspond
to.

**Comment by nathanaeljones** [comment]
Clients can use any convention in the API they expose, of course, but fewer
terms means less to remember.

**Comment by SamuelEnglard** [comment]
I'd follow JSON/JavaScript convention then. That's what's expected when creating JSON.

**Comment by nathanaeljones** [comment]
Is unexpectedly familiar for most and unexpectedly different for some
better than expectedly different for most and expectedly familiar for some?

A large chunk of JSON apis choose camelCase, but not all. What's right for
imageflow? We do have some sentences for keys, and they're really hard to
read in camelCase.

**Comment by SamuelEnglard** [comment]
Most developers would be dealing with clients, no?

**Comment by nathanaeljones** [comment]
Correct. This primarily impacts:

1. Integration test readability
2. Client/wrapper development (some languages with matching conventions can reduce boilerplate)
3. Those using imageflow_tool's JSON API directly. 

My motivation for opening this ticket was the realization that most places where one cares about the schema and casing convention are also places where one will have to map them to different identifiers for convention reasons, doubling the number of symbols in play.  When the API casing convention matches the client casing convention, one only has to develop muscle memory for one form of each name, and often one can avoid writing adapters. This doesn't help (or change, AFAICT) C# wrappers, but would help C, Rust, Ruby, and Python. It would hinder Javascript and possibly Java and PHP.

**Comment by SamuelEnglard** [comment]
My vote is for camelCase

**Comment by nathanaeljones** [comment]
We have a lot of terms with [embedded numbers](https://softwareengineering.stackexchange.com/questions/140699/how-to-camel-case-where-consecutive-words-have-numbers), like "Rotate1D"/"rotate1D"/"rotate_1d". Do you know of a widely understood convention for camelCasing these?

**Comment by nathanaeljones** [comment]
It looks like Google dropped the camelCase recommendation, but still uses it primarily. Twitter, Facebook, and Amazon use snake_case. It's [not standardized](http://stackoverflow.com/a/25368854/166893), but usually influenced by how coupled it is with a Javascript codebase. I think overall snake_case minimizes inconsistencies (adapters are fragile and hard to verify).

I don't usually pick things by popularity, but based on arguments relevant to the thing. For example, here is a counteraguments I suspect but can't verify: 

*There may be a language whose best JSON library either doesn't support snake_case or makes it difficult to use such that likelihood of human error is increased. This may balance out languages where snake_case eliminates high-maintenance code.*

**Comment by SamuelEnglard** [comment]
It maybe my C-based background seeping through but I (personally) like camelCase

**Comment by nathanaeljones** [comment]
I (personally) abhor and loathe camelCase. snake_case is significantly faster to read ([original study results were reproduced - high level of confidence](http://www.cs.kent.edu/~jmaletic/papers/ICPC2010-CamelCaseUnderScoreClouds.pdf)). 

I have little to no interest in bikeshedding stylistic preferences - my own or others. I'm interested in hearing about technical restrictions that could affect the development cost of wrappers and test suites, or confirmed interoperability issues.

Current examples: 
https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/context_json_api.txt
https://s3-us-west-1.amazonaws.com/imageflow-nightlies/master/doc/job_json_api.txt


Relevant technical detail under consideration:

* camelCase is the current convention implemented. It can be changed to snake_case in < 10m. Later, it will be much more difficult, as I'll be storing serialized JSON in test suites. 
* Mixing camelCase and snake_case increases risk of typos. 
* camelCase roughly doubles boilerplate in Ruby wrapper and tests, and the extended test suite will be written in Ruby. This could be mitigated by adding an automated adapter.
* camelCase doubles the number of unique terms in Rust JSON tests, and usually involves more typos.
* snake_case may increase boilerplate or adapter requirements in the Javascript wrapper as camelCase does in Ruby. I don't mind using snake_case in Javascript, but public APIs would likely need to camelCase due to the strong expectation.
* I'm not aware of a way in which the JSON casing style would affect C# wrapper development, but would like to know if there is such a consideration. 
* snake_case and camelCase are bidirectionally convertible in an automated fashion. frame0_width renamed to frame_0_width would permit the following rules: insert an underscore between a non-number and a number, or between a lowercase and uppercase letter, or between a number and an uppercase letter. Lowercase all. When converting to camelCase, uppercase the letter following each underscore (or leave intact if a number). Remove underscores.


There is also the special case of discriminated unions. I've currently (also) mapped some of these to camelCase, but these identifiers are not really members - but rather keys to determine which structure should be used to parse the value. These are typically in the form `{"VariantName": {contentsToParseAsVariantNamed}}`. They always involve a hash with exactly one key, and the parsing schema changes depending on what that key is named. 

The best example of this is Node: https://github.com/imazen/imageflow/blob/master/imageflow_serde/src/lib.rs#L252

Using a different convention for these would indicate that they require special behavior and shouldn't be (for example) addressed directly in a javascript object or ruby hash, as only one could exist. For serialization purposes, it's unclear if this distinction is very important. While our JSON responses include the ResponsePayload discriminated union, you only get the one you'd expect from the endpoint you're talking to. For instructing Imageflow, it's not very relevant, but it could be if you're emulating it or parsing it's syntax.

1. Any thoughts on conventions for discriminated unions?
2. Rust's serde_json doesn't permit aliases for field members, so we can't be permissive of both forms - we have to choose.
3. We could add a test that round-trips all JSON keys, recursively, to ensure the camel<>snake conversion rules are strictly valid. Would this be enough to make this topic a non-issue as far as wrappers go? If so, I will choose based on which convention lets me develop the Rust, Ruby, and Javascript code most quickly overall.

**Comment by SamuelEnglard** [comment]
Based on what you've got I say snake_case does seem to make more sense.

**Comment by nathanaeljones** [comment]
I'm going to spike a Node binding before making the final decision. If it doesn't seem problematic there, I doubt I'll have any regrets.

**Comment by nathanaeljones** [comment]
I take that back. Node bindings are harder than I thought, and I need to publish a new release with access to the JSON API before I complete the Node bindings. I'm going to switch to snake_case in the meantime, but leave the camelCase annotations in place until I'm more confident about this.
